<?php
$tf = $this->plugin('tipformat');
$this->headTitle()->append('Skupna');
?>
<div class="page-header">
    <h2><small><?= $this->translate('Skupina', 'default') ?></small></h2>
</div>
<?php
if ($form) {
    $form->prepare();
    $formHelper = $this->plugin('formtwb');
    $formHelper->setFormType('horizontal');    
    

    echo $formHelper->render($form);    

    if ($form->getMode() == 'EDIT') {
        ?>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <?= $this->translate('Člani skupine', 'default') ?>
                </div>
                <ul class="list-group">
                    <?php
                    foreach ($object->getUsers() as $user) {
                        ?>
                        <li class="list-group-item"><?= $user->getSurname() ?>, <?= $user->getName() ?> (<?= $user->getUsername() ?>)
                            <a class="pull-right" title ="Odstrani uporabnika iz skupine" href="<?=
                            $this->url('aaa', [
                                'controller' => 'Group',
                                'action' => 'odstraniUporabnika',
                                'id' => $object->getId()
                                    ], [
                                'query' => [
                                    'user' => $user->getId()
                                ]
                            ]);
                            ?>"><i class="icon-remove"></i></a>
                        </li>
                               <?php
                           }
                           ?>
                </ul>
            </div>

        <?= $this->userSelect ?>
        </div>


        <?php
    }
}
?>
