<?php
$this->headTitle()->append('Skupine uporabnikov');
$formType = 'inline';
$tf = $this->plugin('tipformat');
$ma = $this->plugin('marionette');
$ma->filter($filter);
?>
<div class="page-header">
    <h2><?= $this->translate('Skupine uporabnikov', 'default') ?></h2>
</div>

<table class="table table-hover table-condensed">
    <thead>
        <tr>
            <th><?= $this->translate('Skupina', 'default') ?></th>
            <th ><?= $this->translate('Opis', 'default') ?></th>
            <th><?= $this->translate('Akcije', 'default') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        if ($paginator) {
            foreach ($paginator as $group) {
                echo $this->partial('aaa/group/listitem', ['group' => $group]);
            }
        }
        ?>
    </tbody>
</table>
<div class="row">
    <div class="col-md-12">
        <?= $paginator ? $this->paginationControl($paginator, 'sliding', 'tip/paginator/standard', array()) : ''; ?>
    </div>
</div>
