<tr>
    <td>
        <a href="<?=
        $this->newtab('aaa', [
            'controller' => 'Group',
            'action' => 'pregled',
            'id' => $group->id
        ])
        ?>"><?= $group->name ?></a>
    </td>
    <td>
        <?= $group->description ?>
    </td>    
    <td>
        <a href="<?=
        $this->url('aaa', [
            'controller' => 'Group',
            'action' => 'brisi',
            'id' => $group->id
        ])
        ?>"><i class="icon-trash"></i></a>
        <a href="<?=
        $this->newtab('aaa', [
            'controller' => 'Group',
            'action' => 'uredi',
            'id' => $group->id
        ])
        ?>"><i class="icon-group"></i></a>
    </td>
</tr>
