<?php

namespace TestAssets\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DokumentRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DokumentRepository extends EntityRepository
{
}
