<?php
$this->headTitle()->append($meta->getI18n()->label);
$tf = $this->plugin('tipformat');
?>

<div class="page-header">
    <h2><small><?= $meta->getI18n()->label ?></small></h2>
</div>
<?php
if ($form) {
    $form->prepare();
    $formHelper = $this->plugin('formtwb');
    echo $formHelper->render($form);
}
?>
<div class = "row">
    <div class = "col-md-9">
        <?= $tf->zadnjaSprememba($object) ?>
    </div>
</div>




