## YAML Template.
---
type: rest
entityClass: Produkcija\Entity\TipFunkcije
forms:
    default: 
        elements:
#            - id
            - name: sifra
              options: 
                 required: false
            - ime
            - opis
            - imeZenski
            - podrocje
#            - funkcije
lists:
    default: 
        filter:
#            elements:                 
#                - name: funkcije
#                  options:
#                      label: Funkcije
#                      targetEntity: Produkcija\Entity\Funkcija
#                      required: true
        hydrator:
            - exclude: []
#    vse: 
#        filter:
    