## YAML Template.
---
type: rest
entityClass: Produkcija\Entity\AvtorBesedila
forms:
    default: 
        elements:
#            - id
            - tipAvtorja
            - zaporedna
            - aliVNaslovu
            - besedilo
            - oseba
        hydrator:
            lookups:
                - oseba
                - besedilo
lists:
    default: 
        filter:
            elements:                 
                - name: besedilo
                  type: toone
                  options:
                      label: Besedilo
                      targetEntity: Produkcija\Entity\Besedilo
                      required: true
        hydrator:
            lookups:
                - oseba
                - besedilo
#    vse: 
#        filter: