## YAML Template.
---
type: rest
entityClass: Produkcija\Entity\Arhivalija
forms:
    default: 
        elements:
#            - id
            - oznakaDatuma
            - datum
            - fizicnaOblika
            - izvorDigitalizata
            - povzetek
            - opombe
            - lokacijaOriginala
            - objavljeno
            - naslov
            - avtorstvo
            - dogodek
            - uprizoritev
lists:
    default: 
        filter:
            elements:                 
                - name: uprizoritev
                  type: toone
                  options:
                      label: Uprizoritev
                      targetEntity: Produkcija\Entity\Uprizoritev
                      required: true
        hydrator:
            - exclude: []
    vse: 
        filter:
