## YAML Template.
---
type: rest
entityClass: Produkcija\Entity\Rekvizit
forms:
    default: 
        elements:
#            - id
            - ime
            - vrsta
#            - rekviziterstva
lists:
    default: 
        filter:
        hydrator:
            - exclude: []
#    vse: 
#        filter:
relation:
    default:
        rekviziterstva:
            enabled: true
            hydrator:
                exclude: []