## YAML Template.
---
type: rest
entityClass: Produkcija\Entity\TipFunkcije
forms:
    default: 
        elements:
#            - id
            - name: sifra
              options: 
                 required: false
            - ime
            - opis
            - imeZenski
            - podrocje
            - sort
#            - funkcije
lists:
    default: 
        filter:
            elements: 
                - name: q
                  type: text
                  options:
                    required: false
                    placeholder: Išči..
                    label: Išči
        hydrator:
            - exclude: []
#    vse: 
#        filter:
    