<?php
$tf = $this->plugin('tipformat');
$this->headTitle()->append('Uporabniki');
$form->prepare();
$formHelper = $this->plugin('formtwb');

$fs = $form->getBaseFieldset();

$helper = $this->plugin('forminputtwb');
$actions = $formHelper->getActions($form);
$actionsHelper = $this->plugin('formactionstwb');
$groupHelper = $this->plugin('formgrouptwb');

echo $formHelper->openTag($form);
?>
<div class="row">
    <div class="col-md-12"></div>
    <div class="col-md-6">
        <?= $groupHelper->render($form, 'Uporabnik') ?>
    </div>
    <div class="col-md-6">
        <?= $groupHelper->render($form, 'Login') ?>
        <?= $groupHelper->render($form, 'Zagon') ?>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <h3><?= $this->translate('Skupine', 'default') ?></h3>
        <ul class="list-group">
            <?php
            $grps = $object->groups;
            foreach ($grps as $grp) {
                ?>
                <li class="list-group-item">
                    <h4 class="list-group-item-heading"><a href="<?=
                        $this->newtab('aaa',
                                [
                            'controller' => 'Group',
                            'action' => 'pregled',
                            'id' => $grp->id])
                        ?>"><?= $grp->name ?></a></h4>
                    <p class="list-group-item-content"> <?= $grp->getDescription() ?></p>

                </li>
            <?php }
            ?>
        </ul>
    </div>
    <div class="col-md-6">
        <h3><?= $this->translate('Vloge', 'default') ?></h3>
        <div class="list-group">
            <ul class="list-group">
                <?php
                foreach ($object->getRoles() as $role) {
                    ?>
                    <li class="list-group-item">
                        <h4 class="list-group-item-heading"> <?= $role->getName() ?></h4>
                        <p class="list-group-item-content"> <?= $role->getDescription() ?> </p>
                    </li>
                    <?php
                }
                ?>
            </ul>
        </div>
    </div>

</div>
<div class="row">
    <div class="col-md-12">
<?= $actionsHelper->render($actions) ?>
    </div>
</div>
<div class = "row">
    <div class = "col-md-9">
<?= $tf->zadnjaSprememba($object) ?>
    </div>
</div>

<?php
echo $formHelper->closeTag();
?>



