<?php
$this->headTitle()->append('Uporabniki');
$tf = $this->plugin('tipformat');
$ma = $this->plugin('marionette');
$ma->filter($filter);
?>

<div class="page-header">
    <h2><?= $this->translate('Uporabniki', 'default') ?></h2>
</div>

<table class="table table-hover table-condensed">
    <thead>
        <tr>
            <th><?= $this->translate('Up. ime', 'default'); ?></th>
            <th><?= $this->translate('Ime', 'default'); ?></th>
            <th><?= $this->translate('Priimek', 'default'); ?></th>
            <th><?= $this->translate('E-Mail', 'default'); ?></th>
            <th><?= $this->translate('Akcije', 'default'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        if ($paginator) {
            foreach ($paginator as $user) {
                echo $this->partial('aaa/user/listitem', ['user' => $user]);
            }
        }
        ?>
    </tbody>
</table>
<div class="row">
    <div class="col-md-12">
        <?php
        if ($paginator) {
            echo $this->paginationControl($paginator, 'sliding', 'tip/paginator/standard', array());
        }
        ?>
    </div>
</div>
