<tr>
    <td> <a href="<?= 
        $this->newtab('aaa', [
            'controller' => 'User',
            'action' => 'pregled',
            'id' => $user->id
        ]) ?>"><?=  $user->username ?></a></td>
    <td><?=  $user->name ?></td>
    <td><?=  $user->surname ?></td>
    <td><?=  $user->email ?></td>
    <td>
        <a href="<?= 
        $this->newtab('aaa', [
            'controller' => 'User',
            'action' => 'brisi',
            'id' => $user->id
        ]) ?>"><i class="icon-trash"></i></a> 
        <a href="<?= $this->newtab('aaa', [
            'controller' => 'User',
            'action' => 'uredi',
            'id' => $user->id
        ]) ?>"><i class="icon-edit"></i></a> 
    </td>
</tr>
