<?php
$title = $this->translate('Prijava v aplikacijo');
$this->headTitle($title);
?>
<div class="page-header">
    <h2>
        <small><?=  $this->escapeHtml($title); ?></small>
    </h2>
</div>
<?php
if ($form) {
    $form->prepare();
    $formHelper = $this->plugin('formtwb');
    ?>

    <div class="clearfix page-header col-md-6">
        <?= $formHelper->render($form, true) ?>
    </div>
    <?php
}
?>
<script type="text/javascript">
    document.getElementById('input-focus').select()
</script>