<?php
$tf = $this->plugin('tipformat');
$this->headTitle()->append('Uporabniki');
?>

<div class="page-header">
    <h2><small><?= $this->translate('Uporabniki', 'default') ?></small></h2>
</div>
<?php
if ($form) {
    $form->prepare();
    $formHelper = $this->plugin('formtwb');

    $fs = $form->getBaseFieldset();

    $helper = $this->plugin('forminputtwb');
    $actions = $formHelper->getActions($form);
    $actionsHelper = $this->plugin('formactionstwb');
    $groupHelper = $this->plugin('formgrouptwb');

    echo $formHelper->openTag($form);
    ?>
    <div class="row">
        <div class="col-md-6">
            <?= $groupHelper->render($form, 'Uporabnik') ?>
        </div>
        <div class="col-md-6">
            <?= $groupHelper->render($form, 'Login') ?>
            <?= $groupHelper->render($form, 'Zagon') ?>
        </div>
    </div>
    <?php
    echo $formHelper->closeTag();
}
?>
<div class="row">
    <div class="col-md-6">
        <h3><?= $this->translate('Skupine', 'default') ?></h3>
        <div class="list-group">
            <?php
            // echo $this->formCollection()->render($form->getBaseFieldset()->get('groups'));
            $grps = $object->groups;
            foreach ($grps as $grp) {
                ?>
                <a  class="list-group-item"  href="<?=
                $this->newtab('aaa', [
                    'controller' => 'Group',
                    'action' => 'pregled',
                    'id' => $grp->id])
                ?>"><h4 class="list-group-item-heading"><?= $grp->name ?></h4>
                    <p class="list-group-item-content"><?= $grp->description ?></p></a>
                <?php
            }
            ?>
        </div>
    </div>
    <?= $this->assignedRoles ?> 
</div>

<div class = "row">
    <div class = "col-md-9">
        <?= $tf->zadnjaSprememba($object) ?>
    </div>
</div>




