<?php

namespace DoctrineORMModule\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20150824004401 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE TABLE Permission (id UUID NOT NULL, name VARCHAR(150) DEFAULT NULL, description TEXT DEFAULT NULL, builtIn BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE revizije (id SERIAL NOT NULL, razred VARCHAR(100) NOT NULL, objectId UUID DEFAULT NULL, upor UUID DEFAULT NULL, datum TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tip VARCHAR(3) NOT NULL, data TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Role (id UUID NOT NULL, name VARCHAR(150) DEFAULT NULL, description TEXT DEFAULT NULL, builtIn BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F75B25545E237E06 ON Role (name)');
        $this->addSql('CREATE TABLE Permission2Role (role_id UUID NOT NULL, permission_id UUID NOT NULL, PRIMARY KEY(role_id, permission_id))');
        $this->addSql('CREATE INDEX IDX_4FF23396D60322AC ON Permission2Role (role_id)');
        $this->addSql('CREATE INDEX IDX_4FF23396FED90CCA ON Permission2Role (permission_id)');
        $this->addSql('CREATE TABLE uporabniki (id UUID NOT NULL, name VARCHAR(255) NOT NULL, password VARCHAR(90) DEFAULT NULL, enabled BOOLEAN DEFAULT NULL, expires DATE DEFAULT NULL, defaultRoute VARCHAR(255) DEFAULT NULL, defaultRouteParams VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, lastLogon DATE DEFAULT NULL, passRestToken VARCHAR(255) DEFAULT NULL, tokenExpires TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Role2User (user_id UUID NOT NULL, role_id UUID NOT NULL, PRIMARY KEY(user_id, role_id))');
        $this->addSql('CREATE INDEX IDX_704D3ABCA76ED395 ON Role2User (user_id)');
        $this->addSql('CREATE INDEX IDX_704D3ABCD60322AC ON Role2User (role_id)');
        $this->addSql('CREATE TABLE Abonma (id UUID NOT NULL, stPredstav INT DEFAULT NULL, stKuponov INT DEFAULT NULL, ime VARCHAR(40) DEFAULT NULL, opis TEXT DEFAULT NULL, kapaciteta INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE drza (id UUID NOT NULL, sifra VARCHAR(2) DEFAULT NULL, sifraDolg VARCHAR(3) DEFAULT NULL, isoNum VARCHAR(3) DEFAULT NULL, isoNaziv VARCHAR(50) DEFAULT NULL, naziv VARCHAR(50) DEFAULT NULL, opomba TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D10C3C4559828A3 ON drza (sifra)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D10C3C4A73E48E1 ON drza (sifraDolg)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D10C3C45841B2E7 ON drza (isoNum)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D10C3C4BEC28CEF ON drza (isoNaziv)');
        $this->addSql('CREATE TABLE KontaktnaOseba (id UUID NOT NULL, popa_id UUID DEFAULT NULL, oseba_id UUID DEFAULT NULL, status VARCHAR(20) DEFAULT NULL, funkcija VARCHAR(255) DEFAULT NULL, opis TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2942B1076BEEDE51 ON KontaktnaOseba (popa_id)');
        $this->addSql('CREATE INDEX IDX_2942B10710389148 ON KontaktnaOseba (oseba_id)');
        $this->addSql('CREATE TABLE Option (id UUID NOT NULL, name VARCHAR(100) NOT NULL, type VARCHAR(20) DEFAULT NULL, defaultValue TEXT DEFAULT NULL, perUser BOOLEAN DEFAULT \'true\', readOnly BOOLEAN DEFAULT NULL, public BOOLEAN DEFAULT NULL, role VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5D2A05865E237E06 ON Option (name)');
        $this->addSql('CREATE TABLE OptionValue (id UUID NOT NULL, option_id UUID DEFAULT NULL, user_id UUID DEFAULT NULL, value TEXT DEFAULT NULL, global BOOLEAN DEFAULT \'false\', PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EF01221FA7C41D6F ON OptionValue (option_id)');
        $this->addSql('CREATE INDEX IDX_EF01221FA76ED395 ON OptionValue (user_id)');
        $this->addSql('CREATE TABLE Oseba (id UUID NOT NULL, user_id UUID DEFAULT NULL, naslov_id UUID DEFAULT NULL, sifra VARCHAR(4) NOT NULL, naziv VARCHAR(40) DEFAULT NULL, ime VARCHAR(255) DEFAULT NULL, priimek VARCHAR(255) DEFAULT NULL, funkcija VARCHAR(40) DEFAULT NULL, srednjeIme VARCHAR(255) DEFAULT NULL, polnoIme VARCHAR(255) DEFAULT NULL, psevdonim VARCHAR(255) DEFAULT NULL, email VARCHAR(40) DEFAULT NULL, datumRojstva DATE DEFAULT NULL, emso VARCHAR(255) DEFAULT NULL, davcna VARCHAR(255) DEFAULT NULL, spol VARCHAR(1) DEFAULT NULL, opombe TEXT DEFAULT NULL, drzavljanstvo VARCHAR(255) DEFAULT NULL, drzavaRojstva VARCHAR(255) DEFAULT NULL, krajRojstva VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_466966D7559828A3 ON Oseba (sifra)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_466966D7A76ED395 ON Oseba (user_id)');
        $this->addSql('CREATE INDEX IDX_466966D769E8D4 ON Oseba (naslov_id)');
        $this->addSql('CREATE TABLE popa (id UUID NOT NULL, drzava_id UUID NOT NULL, sifra VARCHAR(4) NOT NULL, tipkli VARCHAR(20) DEFAULT NULL, stakli VARCHAR(2) DEFAULT NULL, naziv VARCHAR(60) NOT NULL, naziv1 VARCHAR(60) DEFAULT NULL, panoga VARCHAR(60) DEFAULT NULL, email VARCHAR(50) DEFAULT NULL, url VARCHAR(100) DEFAULT NULL, opomba TEXT DEFAULT NULL, idddv VARCHAR(18) DEFAULT NULL, maticna VARCHAR(20) DEFAULT NULL, zavezanec VARCHAR(1) DEFAULT NULL, jeeu VARCHAR(1) DEFAULT NULL, datZav DATE DEFAULT NULL, datnZav DATE DEFAULT NULL, zamejstvo BOOLEAN DEFAULT NULL, nvo BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1C7ADBA5559828A3 ON popa (sifra)');
        $this->addSql('CREATE INDEX IDX_1C7ADBA5EE4B985A ON popa (drzava_id)');
        $this->addSql('CREATE TABLE Posta (id UUID NOT NULL, sifra VARCHAR(20) DEFAULT NULL, naziv VARCHAR(40) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BA25E4B6559828A3 ON Posta (sifra)');
        $this->addSql('CREATE TABLE PostniNaslovi (id UUID NOT NULL, klient_id UUID DEFAULT NULL, oseba_id UUID DEFAULT NULL, drzava_id UUID DEFAULT NULL, naziv VARCHAR(50) DEFAULT NULL, nazivDva VARCHAR(50) DEFAULT NULL, ulica VARCHAR(50) DEFAULT NULL, ulicaDva VARCHAR(50) DEFAULT NULL, posta VARCHAR(50) DEFAULT NULL, postaNaziv VARCHAR(50) DEFAULT NULL, pokrajina VARCHAR(50) DEFAULT NULL, jeeu BOOLEAN DEFAULT NULL, privzeti BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_89C1F9D2A233CB39 ON PostniNaslovi (klient_id)');
        $this->addSql('CREATE INDEX IDX_89C1F9D210389148 ON PostniNaslovi (oseba_id)');
        $this->addSql('CREATE INDEX IDX_89C1F9D2EE4B985A ON PostniNaslovi (drzava_id)');
        $this->addSql('CREATE TABLE Telefonska (id UUID NOT NULL, oseba_id UUID DEFAULT NULL, popa_id UUID DEFAULT NULL, vrsta VARCHAR(20) NOT NULL, stevilka VARCHAR(30) DEFAULT NULL, privzeta BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EF76E55910389148 ON Telefonska (oseba_id)');
        $this->addSql('CREATE INDEX IDX_EF76E5596BEEDE51 ON Telefonska (popa_id)');
        $this->addSql('CREATE TABLE Trr (id UUID NOT NULL, popa_id UUID DEFAULT NULL, oseba_id UUID DEFAULT NULL, stevilka VARCHAR(255) DEFAULT NULL, swift VARCHAR(255) DEFAULT NULL, bic VARCHAR(255) DEFAULT NULL, banka VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_37F6541A6BEEDE51 ON Trr (popa_id)');
        $this->addSql('CREATE INDEX IDX_37F6541A10389148 ON Trr (oseba_id)');
        $this->addSql('CREATE TABLE Dogodek (id UUID NOT NULL, predstava_id UUID DEFAULT NULL, zasedenost_id UUID DEFAULT NULL, vaja_id UUID DEFAULT NULL, gostovanje_id UUID DEFAULT NULL, dogodek_izven_id UUID DEFAULT NULL, prostor_id UUID DEFAULT NULL, sezona_id UUID DEFAULT NULL, planiranZacetek TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, zacetek TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, konec TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status INT DEFAULT NULL, razred VARCHAR(10) DEFAULT NULL, termin VARCHAR(255) DEFAULT NULL, ime VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_11E93B5D5AC894AA ON Dogodek (predstava_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_11E93B5D14A6C237 ON Dogodek (zasedenost_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_11E93B5D18640538 ON Dogodek (vaja_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_11E93B5DEF0F30B ON Dogodek (gostovanje_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_11E93B5D10398482 ON Dogodek (dogodek_izven_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_11E93B5DCC3AA562 ON Dogodek (prostor_id)');
        $this->addSql('CREATE INDEX IDX_11E93B5D3A0E32E3 ON Dogodek (sezona_id)');
        $this->addSql('CREATE INDEX zacetek ON Dogodek (zacetek)');
        $this->addSql('CREATE INDEX konec ON Dogodek (konec)');
        $this->addSql('CREATE TABLE DogodekIzven (id UUID NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Gostovanje (id UUID NOT NULL, drzava_id UUID NOT NULL, vrsta VARCHAR(255) DEFAULT NULL, zamejstvo BOOLEAN DEFAULT NULL, kraj VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CAE790C7EE4B985A ON Gostovanje (drzava_id)');
        $this->addSql('CREATE TABLE Gostujoca (id UUID NOT NULL, uprizoritev_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4A45D07962B4FFCA ON Gostujoca (uprizoritev_id)');
        $this->addSql('CREATE TABLE Predstava (id UUID NOT NULL, uprizoritev_id UUID DEFAULT NULL, gostovanje_id UUID DEFAULT NULL, gostujoc_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_602F6E4662B4FFCA ON Predstava (uprizoritev_id)');
        $this->addSql('CREATE INDEX IDX_602F6E46EF0F30B ON Predstava (gostovanje_id)');
        $this->addSql('CREATE INDEX IDX_602F6E466F7E7A33 ON Predstava (gostujoc_id)');
        $this->addSql('CREATE TABLE Sezona (id UUID NOT NULL, sifra VARCHAR(255) NOT NULL, ime VARCHAR(255) DEFAULT NULL, zacetek DATE DEFAULT NULL, konec DATE DEFAULT NULL, aktivna BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ECC8F8C5559828A3 ON Sezona (sifra)');
        $this->addSql('CREATE TABLE Vaja (id UUID NOT NULL, uprizoritev_id UUID DEFAULT NULL, zaporedna INT DEFAULT NULL, porocilo TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2390FC9662B4FFCA ON Vaja (uprizoritev_id)');
        $this->addSql('CREATE TABLE Zasedenost (id UUID NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE TerminStoritve (id UUID NOT NULL, dogodek_id UUID DEFAULT NULL, alternacija_id UUID DEFAULT NULL, oseba_id UUID NOT NULL, planiranZacetek TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, planiranKonec TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, zacetek TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, konec TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, planiranoTraja NUMERIC(15, 2) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FEF7D84BA81CCEF6 ON TerminStoritve (dogodek_id)');
        $this->addSql('CREATE INDEX IDX_FEF7D84B740EB038 ON TerminStoritve (alternacija_id)');
        $this->addSql('CREATE INDEX IDX_FEF7D84B10389148 ON TerminStoritve (oseba_id)');
        $this->addSql('CREATE TABLE Kupec (id UUID NOT NULL, popa_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D2009BB6BEEDE51 ON Kupec (popa_id)');
        $this->addSql('CREATE TABLE NacinPlacina (id UUID NOT NULL, ime VARCHAR(255) DEFAULT NULL, vrsta VARCHAR(10) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE PlacilniInstrument (id UUID NOT NULL, nacin_placina_id UUID DEFAULT NULL, ime VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1DF2E9FAA420584D ON PlacilniInstrument (nacin_placina_id)');
        $this->addSql('CREATE TABLE PodrocjeSedenja (id UUID NOT NULL, ime VARCHAR(255) DEFAULT NULL, kapaciteta INT DEFAULT NULL, templatePlaceholder VARCHAR(20) DEFAULT NULL, barva VARCHAR(10) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE PostavkaRacuna (id UUID NOT NULL, racun_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_80B6F3595B3D808C ON PostavkaRacuna (racun_id)');
        $this->addSql('CREATE TABLE ProdajaPredstave (id UUID NOT NULL, sedezni_red_id UUID DEFAULT NULL, dogodek_id UUID NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_20D95C7FB31AE31 ON ProdajaPredstave (sedezni_red_id)');
        $this->addSql('CREATE INDEX IDX_20D95C7FA81CCEF6 ON ProdajaPredstave (dogodek_id)');
        $this->addSql('CREATE TABLE Prostor (id UUID NOT NULL, sifra VARCHAR(255) NOT NULL, naziv VARCHAR(255) NOT NULL, jePrizorisce BOOLEAN DEFAULT NULL, kapaciteta INT DEFAULT NULL, opis TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_952DD219559828A3 ON Prostor (sifra)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_952DD21937854736 ON Prostor (naziv)');
        $this->addSql('CREATE TABLE Racun (id UUID NOT NULL, kupec_id UUID DEFAULT NULL, prodaja_predstave_id UUID DEFAULT NULL, nacin_placina_id UUID NOT NULL, placilni_instrument_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B5B84F45BC902D3B ON Racun (kupec_id)');
        $this->addSql('CREATE INDEX IDX_B5B84F45FE7B16E1 ON Racun (prodaja_predstave_id)');
        $this->addSql('CREATE INDEX IDX_B5B84F45A420584D ON Racun (nacin_placina_id)');
        $this->addSql('CREATE INDEX IDX_B5B84F4533341AB8 ON Racun (placilni_instrument_id)');
        $this->addSql('CREATE TABLE RazpisanSedez (id UUID NOT NULL, postavka_racuna_id UUID NOT NULL, sedez_id UUID DEFAULT NULL, prodaja_predstave_id UUID DEFAULT NULL, rezervacija_id UUID DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_667E35D1F5E1D2D3 ON RazpisanSedez (postavka_racuna_id)');
        $this->addSql('CREATE INDEX IDX_667E35D1C146C3F3 ON RazpisanSedez (sedez_id)');
        $this->addSql('CREATE INDEX IDX_667E35D1FE7B16E1 ON RazpisanSedez (prodaja_predstave_id)');
        $this->addSql('CREATE INDEX IDX_667E35D117619010 ON RazpisanSedez (rezervacija_id)');
        $this->addSql('CREATE TABLE Rezervacija (id UUID NOT NULL, prodaja_predstave_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_48F1F62BFE7B16E1 ON Rezervacija (prodaja_predstave_id)');
        $this->addSql('CREATE TABLE Sedez (id UUID NOT NULL, vrsta_id UUID NOT NULL, sedezni_red_id UUID DEFAULT NULL, podrocja_sedenja_id UUID DEFAULT NULL, stevilka VARCHAR(3) DEFAULT NULL, oznaka VARCHAR(60) DEFAULT NULL, kakovost VARCHAR(20) DEFAULT NULL, koordinataX INT DEFAULT NULL, koordinataY INT DEFAULT NULL, barva VARCHAR(10) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_52ED210BEF943358 ON Sedez (vrsta_id)');
        $this->addSql('CREATE INDEX IDX_52ED210BB31AE31 ON Sedez (sedezni_red_id)');
        $this->addSql('CREATE INDEX IDX_52ED210B1C0DC15A ON Sedez (podrocja_sedenja_id)');
        $this->addSql('CREATE TABLE SedezniRed (id UUID NOT NULL, kapaciteta INT DEFAULT NULL, ime VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE VrstaSedezev (id UUID NOT NULL, podrocja_sedenja_id UUID NOT NULL, kapaciteta INT DEFAULT NULL, poravnava VARCHAR(255) DEFAULT NULL, oblika VARCHAR(2) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7069C3C41C0DC15A ON VrstaSedezev (podrocja_sedenja_id)');
        $this->addSql('CREATE TABLE Alternacija (id UUID NOT NULL, funkcija_id UUID DEFAULT NULL, zaposlitev_id UUID DEFAULT NULL, oseba_id UUID DEFAULT NULL, pogodba_id UUID DEFAULT NULL, sifra VARCHAR(255) NOT NULL, zaposlen BOOLEAN DEFAULT NULL, zacetek DATE DEFAULT NULL, konec DATE DEFAULT NULL, opomba TEXT DEFAULT NULL, sort INT DEFAULT NULL, privzeti BOOLEAN DEFAULT NULL, aktivna BOOLEAN DEFAULT NULL, imaPogodbo BOOLEAN DEFAULT NULL, pomembna BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A4B7244F559828A3 ON Alternacija (sifra)');
        $this->addSql('CREATE INDEX IDX_A4B7244F861BAED2 ON Alternacija (funkcija_id)');
        $this->addSql('CREATE INDEX IDX_A4B7244FA4976613 ON Alternacija (zaposlitev_id)');
        $this->addSql('CREATE INDEX IDX_A4B7244F10389148 ON Alternacija (oseba_id)');
        $this->addSql('CREATE INDEX IDX_A4B7244F5BC4D310 ON Alternacija (pogodba_id)');
        $this->addSql('CREATE TABLE Arhivalija (id UUID NOT NULL, dogodek_id UUID DEFAULT NULL, uprizoritev_id UUID DEFAULT NULL, oznakaDatuma VARCHAR(255) DEFAULT NULL, datum DATE DEFAULT NULL, fizicnaOblika VARCHAR(255) DEFAULT NULL, izvorDigitalizata VARCHAR(255) DEFAULT NULL, povzetek TEXT DEFAULT NULL, opombe TEXT DEFAULT NULL, lokacijaOriginala VARCHAR(255) DEFAULT NULL, objavljeno VARCHAR(255) DEFAULT NULL, naslov VARCHAR(255) DEFAULT NULL, avtorstvo VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BBFF8755A81CCEF6 ON Arhivalija (dogodek_id)');
        $this->addSql('CREATE INDEX IDX_BBFF875562B4FFCA ON Arhivalija (uprizoritev_id)');
        $this->addSql('CREATE TABLE Besedilo (id UUID NOT NULL, stevilka VARCHAR(255) NOT NULL, naslov VARCHAR(255) DEFAULT NULL, avtor VARCHAR(255) DEFAULT NULL, podnaslov VARCHAR(255) DEFAULT NULL, jezik VARCHAR(255) DEFAULT NULL, naslovIzvirnika VARCHAR(255) DEFAULT NULL, internacionalniNaslov VARCHAR(255) DEFAULT NULL, datumPrejema DATE DEFAULT NULL, moskeVloge INT DEFAULT NULL, zenskeVloge INT DEFAULT NULL, prevajalec VARCHAR(255) DEFAULT NULL, povzetekVsebine TEXT DEFAULT NULL, letoIzida INT DEFAULT NULL, krajIzida VARCHAR(255) DEFAULT NULL, zaloznik VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Funkcija (id UUID NOT NULL, uprizoritev_id UUID NOT NULL, alternacija_id UUID DEFAULT NULL, podrocje VARCHAR(20) DEFAULT NULL, vodjaEkipe BOOLEAN DEFAULT NULL, naziv VARCHAR(255) DEFAULT NULL, komentar VARCHAR(255) DEFAULT NULL, velikost VARCHAR(255) DEFAULT NULL, pomembna BOOLEAN NOT NULL, sort INT DEFAULT NULL, sePlanira BOOLEAN NOT NULL, dovoliPrekrivanje BOOLEAN NOT NULL, maxPrekrivanj INT DEFAULT NULL, tipFunkcije_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_23AEB95862B4FFCA ON Funkcija (uprizoritev_id)');
        $this->addSql('CREATE INDEX IDX_23AEB958740EB038 ON Funkcija (alternacija_id)');
        $this->addSql('CREATE INDEX IDX_23AEB9586B361365 ON Funkcija (tipFunkcije_id)');
        $this->addSql('CREATE TABLE Pogodba (id UUID NOT NULL, oseba_id UUID DEFAULT NULL, popa_id UUID DEFAULT NULL, trr_id UUID DEFAULT NULL, sifra VARCHAR(7) NOT NULL, zacetek DATE DEFAULT NULL, konec DATE DEFAULT NULL, placiloNaVajo BOOLEAN DEFAULT NULL, vrednostVaje NUMERIC(12, 2) DEFAULT NULL, planiranoSteviloVaj INT DEFAULT NULL, vrednostVaj NUMERIC(12, 2) DEFAULT NULL, vrednostPredstave NUMERIC(12, 2) DEFAULT NULL, vrednostDoPremiere NUMERIC(12, 2) DEFAULT NULL, aktivna BOOLEAN DEFAULT NULL, zaposlenVDrJz BOOLEAN DEFAULT NULL, samozaposlen BOOLEAN DEFAULT NULL, igralec BOOLEAN DEFAULT NULL, opis TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2DECFC59559828A3 ON Pogodba (sifra)');
        $this->addSql('CREATE INDEX IDX_2DECFC5910389148 ON Pogodba (oseba_id)');
        $this->addSql('CREATE INDEX IDX_2DECFC596BEEDE51 ON Pogodba (popa_id)');
        $this->addSql('CREATE INDEX IDX_2DECFC59FA5529EE ON Pogodba (trr_id)');
        $this->addSql('CREATE TABLE Rekvizit (id UUID NOT NULL, ime VARCHAR(255) DEFAULT NULL, vrsta VARCHAR(255) DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Rekviziterstvo (id UUID NOT NULL, rekvizit_id UUID DEFAULT NULL, uprizoritev_id UUID DEFAULT NULL, namenUporabe BOOLEAN DEFAULT NULL, opisPostavitve TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8198265413E60BC0 ON Rekviziterstvo (rekvizit_id)');
        $this->addSql('CREATE INDEX IDX_8198265462B4FFCA ON Rekviziterstvo (uprizoritev_id)');
        $this->addSql('CREATE TABLE StrosekUprizoritve (id UUID NOT NULL, uprizoritev_id UUID DEFAULT NULL, popa_id UUID DEFAULT NULL, naziv VARCHAR(255) DEFAULT NULL, vrednostDo NUMERIC(15, 2) DEFAULT NULL, vrednostNa NUMERIC(15, 2) DEFAULT NULL, opis TEXT DEFAULT NULL, tipstroska VARCHAR(10) NOT NULL, sort INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_11FFE6E062B4FFCA ON StrosekUprizoritve (uprizoritev_id)');
        $this->addSql('CREATE INDEX IDX_11FFE6E06BEEDE51 ON StrosekUprizoritve (popa_id)');
        $this->addSql('CREATE TABLE TipFunkcije (id UUID NOT NULL, ime VARCHAR(255) DEFAULT NULL, opis TEXT DEFAULT NULL, imeZenski VARCHAR(255) DEFAULT NULL, podrocje VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Uprizoritev (id UUID NOT NULL, besedilo_id UUID DEFAULT NULL, zvrst_uprizoritve_id UUID DEFAULT NULL, zvrst_surs_id UUID DEFAULT NULL, producent_id UUID DEFAULT NULL, sifra VARCHAR(255) NOT NULL, faza VARCHAR(35) DEFAULT NULL, naslov VARCHAR(255) DEFAULT NULL, podnaslov VARCHAR(255) DEFAULT NULL, delovniNaslov VARCHAR(255) DEFAULT NULL, internacionalniNaslov VARCHAR(255) DEFAULT NULL, datumZacStudija DATE DEFAULT NULL, steviloVaj INT DEFAULT NULL, planiranoSteviloVaj INT DEFAULT NULL, datumPremiere DATE DEFAULT NULL, stOdmorov INT DEFAULT NULL, avtor VARCHAR(255) DEFAULT NULL, gostujoca BOOLEAN DEFAULT NULL, trajanje INT DEFAULT NULL, opis TEXT DEFAULT NULL, arhIdent VARCHAR(255) DEFAULT NULL, arhOpomba VARCHAR(255) DEFAULT NULL, datumZakljucka DATE DEFAULT NULL, sloAvtor BOOLEAN DEFAULT NULL, kratkiNaslov VARCHAR(255) DEFAULT NULL, maticniOder_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_344A77A559828A3 ON Uprizoritev (sifra)');
        $this->addSql('CREATE INDEX IDX_344A77A7C3B0D59 ON Uprizoritev (maticniOder_id)');
        $this->addSql('CREATE INDEX IDX_344A77AF35157B1 ON Uprizoritev (besedilo_id)');
        $this->addSql('CREATE INDEX IDX_344A77A8E27EB8D ON Uprizoritev (zvrst_uprizoritve_id)');
        $this->addSql('CREATE INDEX IDX_344A77A3B262815 ON Uprizoritev (zvrst_surs_id)');
        $this->addSql('CREATE INDEX IDX_344A77A853A965C ON Uprizoritev (producent_id)');
        $this->addSql('CREATE TABLE Zaposlitev (id UUID NOT NULL, oseba_id UUID DEFAULT NULL, sifra VARCHAR(10) NOT NULL, status VARCHAR(10) NOT NULL, zacetek DATE DEFAULT NULL, konec DATE DEFAULT NULL, tip INT DEFAULT NULL, delovnaObveza INT DEFAULT NULL, malica VARCHAR(255) DEFAULT NULL, izmenskoDelo BOOLEAN DEFAULT NULL, individualnaPogodba BOOLEAN DEFAULT NULL, jeZaposlenVdrugemJz BOOLEAN DEFAULT NULL, jeNastopajoci BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B244904110389148 ON Zaposlitev (oseba_id)');
        $this->addSql('CREATE TABLE ZvrstSurs (id UUID NOT NULL, sifra VARCHAR(255) NOT NULL, naziv VARCHAR(255) DEFAULT NULL, opis TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CEDE8E36559828A3 ON ZvrstSurs (sifra)');
        $this->addSql('CREATE TABLE ZvrstUprizoritve (id UUID NOT NULL, sifra VARCHAR(255) NOT NULL, naziv VARCHAR(255) DEFAULT NULL, opis TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5216FCB0559828A3 ON ZvrstUprizoritve (sifra)');
        $this->addSql('CREATE TABLE DrugiVir (id UUID NOT NULL, znesek NUMERIC(15, 2) DEFAULT \'0\' NOT NULL, opis VARCHAR(255) NOT NULL, mednarodni BOOLEAN DEFAULT NULL, enotaPrograma_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E7D4CF2638C06EB ON DrugiVir (enotaPrograma_id)');
        $this->addSql('CREATE TABLE EnotaPrograma (id UUID NOT NULL, uprizoritev_id UUID DEFAULT NULL, program_dela_id UUID DEFAULT NULL, gostitelj_id UUID DEFAULT NULL, celotnaVrednost NUMERIC(15, 2) DEFAULT \'0\' NOT NULL, nasDelez NUMERIC(15, 2) DEFAULT \'0\' NOT NULL, celotnaVrednostMat NUMERIC(15, 2) DEFAULT \'0\' NOT NULL, celotnaVrednostGostovSZ NUMERIC(15, 2) DEFAULT \'0\' NOT NULL, zaproseno NUMERIC(15, 2) DEFAULT \'0\' NOT NULL, lastnaSredstva NUMERIC(15, 2) DEFAULT \'0\' NOT NULL, avtorskiHonorarji NUMERIC(15, 2) DEFAULT \'0\' NOT NULL, avtorskiHonorarjiSamoz NUMERIC(15, 2) DEFAULT \'0\' NOT NULL, tantieme NUMERIC(15, 2) DEFAULT \'0\' NOT NULL, avtorskePravice NUMERIC(15, 2) DEFAULT \'0\' NOT NULL, materialni NUMERIC(15, 2) DEFAULT \'0\' NOT NULL, imaKoprodukcije BOOLEAN DEFAULT NULL, vlozekGostitelja NUMERIC(15, 2) DEFAULT \'0\' NOT NULL, drugiJavni NUMERIC(15, 2) DEFAULT \'0\' NOT NULL, stZaposlenih INT DEFAULT 0 NOT NULL, stZaposUmet INT DEFAULT 0 NOT NULL, stZaposDrug INT DEFAULT 0 NOT NULL, stHonorarnih INT DEFAULT NULL, stHonorarnihIgr INT DEFAULT NULL, stHonorarnihIgrTujJZ INT DEFAULT NULL, stHonorarnihIgrSamoz INT DEFAULT NULL, obiskDoma INT DEFAULT 0 NOT NULL, obiskGost INT DEFAULT 0 NOT NULL, obiskZamejo INT DEFAULT 0 NOT NULL, obiskInt INT DEFAULT 0 NOT NULL, ponoviDoma INT DEFAULT  0 NOT NULL, ponoviZamejo INT DEFAULT 0 NOT NULL, ponoviGost INT DEFAULT 0 NOT NULL, ponoviInt INT DEFAULT 0 NOT NULL, naziv VARCHAR(50) DEFAULT NULL, sort INT DEFAULT NULL, tipProgramskeEnote_id UUID DEFAULT NULL, tip VARCHAR(20) NOT NULL, strosekOdkPred NUMERIC(15, 2) DEFAULT \'0\', stroskiOstali NUMERIC(15, 2) DEFAULT \'0\', krajGostovanja VARCHAR(255) DEFAULT NULL, ustanova VARCHAR(255) DEFAULT NULL, datumGostovanja DATE DEFAULT NULL, transportniStroski NUMERIC(15, 2) DEFAULT NULL, dnevPrvZad NUMERIC(15, 2) DEFAULT NULL, drzavaGostovanja_id UUID DEFAULT NULL, stPE INT DEFAULT 0, zvrst VARCHAR(255) DEFAULT NULL, stPredstav INT DEFAULT NULL, stOkroglihMiz INT DEFAULT NULL, stPredstavitev INT DEFAULT NULL, stDelavnic INT DEFAULT NULL, stDrugiDogodki INT DEFAULT NULL, stProdukcij INT DEFAULT NULL, casPriprave VARCHAR(255) DEFAULT NULL, casIzvedbe VARCHAR(255) DEFAULT NULL, prizorisca TEXT DEFAULT NULL, umetVodja VARCHAR(255) DEFAULT NULL, programskoTelo VARCHAR(255) DEFAULT NULL, stTujihSelektorjev INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8787A0E562B4FFCA ON EnotaPrograma (uprizoritev_id)');
        $this->addSql('CREATE INDEX IDX_8787A0E57222D84B ON EnotaPrograma (tipProgramskeEnote_id)');
        $this->addSql('CREATE INDEX IDX_8787A0E5771EC7BD ON EnotaPrograma (program_dela_id)');
        $this->addSql('CREATE INDEX IDX_8787A0E55D0DA56C ON EnotaPrograma (drzavaGostovanja_id)');
        $this->addSql('CREATE INDEX IDX_8787A0E54AE1CD1C ON EnotaPrograma (gostitelj_id)');
        $this->addSql('CREATE TABLE ProdukcijaDelitev (id UUID NOT NULL, koproducent_id UUID NOT NULL, odstotekFinanciranja NUMERIC(15, 2) DEFAULT NULL, delez NUMERIC(15, 2) DEFAULT NULL, zaproseno NUMERIC(15, 2) DEFAULT NULL, maticniKop BOOLEAN NOT NULL, enotaPrograma_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_97AF082E38C06EB ON ProdukcijaDelitev (enotaPrograma_id)');
        $this->addSql('CREATE INDEX IDX_97AF082EC532925B ON ProdukcijaDelitev (koproducent_id)');
        $this->addSql('CREATE TABLE ProdukcijskaHisa (id UUID NOT NULL, popa_id UUID DEFAULT NULL, sifra VARCHAR(4) NOT NULL, status VARCHAR(20) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E6FC2028559828A3 ON ProdukcijskaHisa (sifra)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E6FC20286BEEDE51 ON ProdukcijskaHisa (popa_id)');
        $this->addSql('CREATE TABLE ProgramDela (id UUID NOT NULL, sezona_id UUID DEFAULT NULL, sifra VARCHAR(255) NOT NULL, naziv VARCHAR(255) NOT NULL, zacetek DATE NOT NULL, konec DATE NOT NULL, zakljuceno BOOLEAN NOT NULL, potrjenProgram BOOLEAN NOT NULL, stPremier INT DEFAULT NULL, stInt INT DEFAULT NULL, stFest INT DEFAULT NULL, stRazno INT DEFAULT NULL, stIzjem INT DEFAULT NULL, stPonPrem INT DEFAULT NULL, stPonPrej INT DEFAULT NULL, stPonPrejVelikih INT DEFAULT NULL, stPonPrejMalih INT DEFAULT NULL, stPonPrejMalihKopr INT DEFAULT NULL, stPonPrejSredKopr INT DEFAULT NULL, stPonPrejVelikihKopr INT DEFAULT NULL, stGostujo INT DEFAULT NULL, vrPS1 NUMERIC(12, 2) DEFAULT NULL, vrPS1Do NUMERIC(12, 2) DEFAULT NULL, vrPS1Mat NUMERIC(12, 2) DEFAULT NULL, vrPS1GostovSZ NUMERIC(12, 2) DEFAULT NULL, stIzvNekomerc INT DEFAULT NULL, stIzvPrem INT DEFAULT NULL, stIzvPonPrem INT DEFAULT NULL, stIzvPonPrej INT DEFAULT NULL, stIzvGostuj INT DEFAULT NULL, stIzvOstalihNek INT DEFAULT NULL, stIzvGostovanjSlo INT DEFAULT NULL, stIzvGostovanjZam INT DEFAULT NULL, stIzvGostovanjInt INT DEFAULT NULL, stObiskNekom INT DEFAULT NULL, stObiskNekomMat INT DEFAULT NULL, stObiskNekomGostSlo INT DEFAULT NULL, stObiskNekomGostZam INT DEFAULT NULL, stObiskNekomGostInt INT DEFAULT NULL, avgObiskPrired NUMERIC(12, 2) DEFAULT NULL, avgZasedDvoran NUMERIC(12, 2) DEFAULT NULL, avgCenaVstopnice NUMERIC(12, 2) DEFAULT NULL, stProdVstopnic INT DEFAULT NULL, stKoprodukcij INT DEFAULT NULL, stKoprodukcijInt INT DEFAULT NULL, stKoprodukcijNVO INT DEFAULT NULL, stZaposlenih INT DEFAULT NULL, stZaposIgralcev INT DEFAULT NULL, avgStNastopovIgr NUMERIC(12, 2) DEFAULT NULL, stHonorarnih INT DEFAULT NULL, stHonorarnihIgr INT DEFAULT NULL, stHonorarnihIgrTujJZ INT DEFAULT NULL, stHonorarnihIgrSamoz INT DEFAULT NULL, sredstvaInt NUMERIC(12, 2) DEFAULT NULL, sredstvaAvt NUMERIC(12, 2) DEFAULT NULL, sredstvaZaprosenoPrem NUMERIC(12, 2) DEFAULT NULL, sredstvaZaprosenoPonPrem NUMERIC(12, 2) DEFAULT NULL, sredstvaZaprosenoPonPrej NUMERIC(12, 2) DEFAULT NULL, sredstvaZaprosenoGostujo NUMERIC(12, 2) DEFAULT NULL, sredstvaZaprosenoInt NUMERIC(12, 2) DEFAULT NULL, sredstvaZaprosenoFest NUMERIC(12, 2) DEFAULT NULL, sredstvaZaprosenoRazno NUMERIC(12, 2) DEFAULT NULL, sredstvaZaprosenoIzjem NUMERIC(12, 2) DEFAULT NULL, sredstvaDrugiJavniPrem NUMERIC(12, 2) DEFAULT NULL, sredstvaDrugiJavniPonPrem NUMERIC(12, 2) DEFAULT NULL, sredstvaDrugiJavniPonPrej NUMERIC(12, 2) DEFAULT NULL, sredstvaDrugiJavniGostujo NUMERIC(12, 2) DEFAULT NULL, sredstvaDrugiJavniInt NUMERIC(12, 2) DEFAULT NULL, sredstvaDrugiJavniFest NUMERIC(12, 2) DEFAULT NULL, sredstvaDrugiJavniRazno NUMERIC(12, 2) DEFAULT NULL, sredstvaDrugiJavniIzjem NUMERIC(12, 2) DEFAULT NULL, sredstvaDrugiViriPrem NUMERIC(12, 2) DEFAULT NULL, sredstvaDrugiViriPonPrem NUMERIC(12, 2) DEFAULT NULL, sredstvaDrugiViriPonPrej NUMERIC(12, 2) DEFAULT NULL, sredstvaDrugiViriGostujo NUMERIC(12, 2) DEFAULT NULL, sredstvaDrugiViriInt NUMERIC(12, 2) DEFAULT NULL, sredstvaDrugiViriFest NUMERIC(12, 2) DEFAULT NULL, sredstvaDrugiViriRazno NUMERIC(12, 2) DEFAULT NULL, sredstvaDrugiViriIzjem NUMERIC(12, 2) DEFAULT NULL, sredstvaAvtSamoz NUMERIC(12, 2) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C81BC37F3A0E32E3 ON ProgramDela (sezona_id)');
        $this->addSql('CREATE TABLE ProgramskaEnotaSklopa (id UUID NOT NULL, naslovPE VARCHAR(255) NOT NULL, avtorPE VARCHAR(255) NOT NULL, obsegPE VARCHAR(255) NOT NULL, mesecPE VARCHAR(255) NOT NULL, vrednostPE NUMERIC(15, 2) DEFAULT \'0\' NOT NULL, programRazno_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2D901816D6BC69D6 ON ProgramskaEnotaSklopa (programRazno_id)');
        $this->addSql('CREATE TABLE TipProgramskeEnote (id UUID NOT NULL, sifra VARCHAR(255) NOT NULL, naziv VARCHAR(255) NOT NULL, koprodukcija BOOLEAN DEFAULT \'false\' NOT NULL, maxFaktor NUMERIC(15, 2) DEFAULT \'1\' NOT NULL, maxVsi NUMERIC(15, 2) DEFAULT \'0\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Stevilcenje (id UUID NOT NULL, sifra VARCHAR(8) DEFAULT NULL, naziv VARCHAR(100) DEFAULT NULL, prefix VARCHAR(5) DEFAULT NULL, suffix VARCHAR(5) DEFAULT NULL, zacetek INT DEFAULT NULL, dolzina INT DEFAULT NULL, format VARCHAR(20) DEFAULT NULL, globalno BOOLEAN DEFAULT NULL, poLetih BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5A434FBC559828A3 ON Stevilcenje (sifra)');
        $this->addSql('CREATE TABLE StevilcenjeKonfig (id UUID NOT NULL, stevilcenje_id UUID DEFAULT NULL, dok VARCHAR(100) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6054E804889A7556 ON StevilcenjeKonfig (dok)');
        $this->addSql('CREATE INDEX IDX_6054E804FF55F926 ON StevilcenjeKonfig (stevilcenje_id)');
        $this->addSql('CREATE TABLE StevilcenjeStanje (id UUID NOT NULL, objId UUID NOT NULL, leto INT NOT NULL, stevilka INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Datoteka (id UUID NOT NULL, owner_id UUID DEFAULT NULL, filename VARCHAR(255) DEFAULT NULL, transfers INT NOT NULL, size INT DEFAULT NULL, format VARCHAR(255) DEFAULT NULL, hash UUID DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uploadedAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, upor VARCHAR(10) DEFAULT NULL, datKnj TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_781826C67E3C61F9 ON Datoteka (owner_id)');
        $this->addSql('CREATE TABLE Mapa (id UUID NOT NULL, lastnik_id UUID DEFAULT NULL, parent_id UUID DEFAULT NULL, ime VARCHAR(200) NOT NULL, komentar TEXT DEFAULT NULL, casKreiranja TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, casSpremembe TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, javniDostop VARCHAR(20) NOT NULL, upor VARCHAR(10) DEFAULT NULL, datKnj TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_14A5D6D38A4A6C12 ON Mapa (lastnik_id)');
        $this->addSql('CREATE INDEX IDX_14A5D6D3727ACA70 ON Mapa (parent_id)');
        $this->addSql('CREATE TABLE mapa_zapis (mapa_id UUID NOT NULL, zapis_id UUID NOT NULL, PRIMARY KEY(mapa_id, zapis_id))');
        $this->addSql('CREATE INDEX IDX_E9F8EE8257ED422F ON mapa_zapis (mapa_id)');
        $this->addSql('CREATE INDEX IDX_E9F8EE82AF91ECD ON mapa_zapis (zapis_id)');
        $this->addSql('CREATE TABLE MapaAcl (id UUID NOT NULL, mapa_id UUID DEFAULT NULL, perm_id UUID DEFAULT NULL, dostop VARCHAR(20) NOT NULL, upor VARCHAR(10) DEFAULT NULL, datKnj TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7ADC957157ED422F ON MapaAcl (mapa_id)');
        $this->addSql('CREATE INDEX IDX_7ADC9571FA6311EF ON MapaAcl (perm_id)');
        $this->addSql('CREATE TABLE VrstaZapisa (id UUID NOT NULL, oznaka VARCHAR(10) NOT NULL, naziv VARCHAR(255) NOT NULL, aktiven BOOLEAN DEFAULT NULL, znacka BOOLEAN DEFAULT NULL, ikona VARCHAR(255) DEFAULT NULL, upor VARCHAR(10) DEFAULT NULL, datKnj TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DE1C8AA1D55226C7 ON VrstaZapisa (oznaka)');
        $this->addSql('CREATE TABLE Zapis (id UUID NOT NULL, vrsta_id UUID DEFAULT NULL, datoteka_id UUID DEFAULT NULL, mapa_id UUID DEFAULT NULL, avtor_id UUID DEFAULT NULL, zaklenil_id UUID DEFAULT NULL, tip VARCHAR(20) NOT NULL, zaklenjen BOOLEAN DEFAULT NULL, datumZaklepanja TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, identifier VARCHAR(20) DEFAULT NULL, subject VARCHAR(255) DEFAULT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, coverage VARCHAR(255) DEFAULT NULL, creator VARCHAR(255) DEFAULT NULL, language VARCHAR(20) DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, publisher VARCHAR(255) DEFAULT NULL, relation VARCHAR(255) DEFAULT NULL, rights VARCHAR(255) DEFAULT NULL, source VARCHAR(255) DEFAULT NULL, upor VARCHAR(10) DEFAULT NULL, datKnj TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, standard VARCHAR(255) DEFAULT NULL, lokacija VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1ED92829EF943358 ON Zapis (vrsta_id)');
        $this->addSql('CREATE INDEX IDX_1ED92829A54DBB1F ON Zapis (datoteka_id)');
        $this->addSql('CREATE INDEX IDX_1ED9282957ED422F ON Zapis (mapa_id)');
        $this->addSql('CREATE INDEX IDX_1ED92829253C4123 ON Zapis (avtor_id)');
        $this->addSql('CREATE INDEX IDX_1ED9282987FF3295 ON Zapis (zaklenil_id)');
        $this->addSql('CREATE TABLE ZapisLastnik (id UUID NOT NULL, zapis_id UUID DEFAULT NULL, lastnik UUID NOT NULL, classLastnika VARCHAR(200) NOT NULL, datum TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, upor VARCHAR(10) DEFAULT NULL, datKnj TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2EAFF9DCAF91ECD ON ZapisLastnik (zapis_id)');
        $this->addSql('ALTER TABLE Permission2Role ADD CONSTRAINT FK_4FF23396D60322AC FOREIGN KEY (role_id) REFERENCES Role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Permission2Role ADD CONSTRAINT FK_4FF23396FED90CCA FOREIGN KEY (permission_id) REFERENCES Permission (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Role2User ADD CONSTRAINT FK_704D3ABCA76ED395 FOREIGN KEY (user_id) REFERENCES uporabniki (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Role2User ADD CONSTRAINT FK_704D3ABCD60322AC FOREIGN KEY (role_id) REFERENCES Role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE KontaktnaOseba ADD CONSTRAINT FK_2942B1076BEEDE51 FOREIGN KEY (popa_id) REFERENCES popa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE KontaktnaOseba ADD CONSTRAINT FK_2942B10710389148 FOREIGN KEY (oseba_id) REFERENCES Oseba (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE OptionValue ADD CONSTRAINT FK_EF01221FA7C41D6F FOREIGN KEY (option_id) REFERENCES Option (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE OptionValue ADD CONSTRAINT FK_EF01221FA76ED395 FOREIGN KEY (user_id) REFERENCES uporabniki (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Oseba ADD CONSTRAINT FK_466966D7A76ED395 FOREIGN KEY (user_id) REFERENCES uporabniki (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Oseba ADD CONSTRAINT FK_466966D769E8D4 FOREIGN KEY (naslov_id) REFERENCES PostniNaslovi (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE popa ADD CONSTRAINT FK_1C7ADBA5EE4B985A FOREIGN KEY (drzava_id) REFERENCES drza (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE PostniNaslovi ADD CONSTRAINT FK_89C1F9D2A233CB39 FOREIGN KEY (klient_id) REFERENCES popa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE PostniNaslovi ADD CONSTRAINT FK_89C1F9D210389148 FOREIGN KEY (oseba_id) REFERENCES Oseba (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE PostniNaslovi ADD CONSTRAINT FK_89C1F9D2EE4B985A FOREIGN KEY (drzava_id) REFERENCES drza (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Telefonska ADD CONSTRAINT FK_EF76E55910389148 FOREIGN KEY (oseba_id) REFERENCES Oseba (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Telefonska ADD CONSTRAINT FK_EF76E5596BEEDE51 FOREIGN KEY (popa_id) REFERENCES popa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Trr ADD CONSTRAINT FK_37F6541A6BEEDE51 FOREIGN KEY (popa_id) REFERENCES popa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Trr ADD CONSTRAINT FK_37F6541A10389148 FOREIGN KEY (oseba_id) REFERENCES Oseba (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Dogodek ADD CONSTRAINT FK_11E93B5D5AC894AA FOREIGN KEY (predstava_id) REFERENCES Predstava (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Dogodek ADD CONSTRAINT FK_11E93B5D14A6C237 FOREIGN KEY (zasedenost_id) REFERENCES Zasedenost (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Dogodek ADD CONSTRAINT FK_11E93B5D18640538 FOREIGN KEY (vaja_id) REFERENCES Vaja (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Dogodek ADD CONSTRAINT FK_11E93B5DEF0F30B FOREIGN KEY (gostovanje_id) REFERENCES Gostovanje (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Dogodek ADD CONSTRAINT FK_11E93B5D10398482 FOREIGN KEY (dogodek_izven_id) REFERENCES DogodekIzven (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Dogodek ADD CONSTRAINT FK_11E93B5DCC3AA562 FOREIGN KEY (prostor_id) REFERENCES Prostor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Dogodek ADD CONSTRAINT FK_11E93B5D3A0E32E3 FOREIGN KEY (sezona_id) REFERENCES Sezona (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Gostovanje ADD CONSTRAINT FK_CAE790C7EE4B985A FOREIGN KEY (drzava_id) REFERENCES drza (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Gostujoca ADD CONSTRAINT FK_4A45D07962B4FFCA FOREIGN KEY (uprizoritev_id) REFERENCES Uprizoritev (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Predstava ADD CONSTRAINT FK_602F6E4662B4FFCA FOREIGN KEY (uprizoritev_id) REFERENCES Uprizoritev (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Predstava ADD CONSTRAINT FK_602F6E46EF0F30B FOREIGN KEY (gostovanje_id) REFERENCES Gostovanje (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Predstava ADD CONSTRAINT FK_602F6E466F7E7A33 FOREIGN KEY (gostujoc_id) REFERENCES Gostujoca (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Vaja ADD CONSTRAINT FK_2390FC9662B4FFCA FOREIGN KEY (uprizoritev_id) REFERENCES Uprizoritev (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE TerminStoritve ADD CONSTRAINT FK_FEF7D84BA81CCEF6 FOREIGN KEY (dogodek_id) REFERENCES Dogodek (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE TerminStoritve ADD CONSTRAINT FK_FEF7D84B740EB038 FOREIGN KEY (alternacija_id) REFERENCES Alternacija (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE TerminStoritve ADD CONSTRAINT FK_FEF7D84B10389148 FOREIGN KEY (oseba_id) REFERENCES Oseba (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Kupec ADD CONSTRAINT FK_2D2009BB6BEEDE51 FOREIGN KEY (popa_id) REFERENCES popa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE PlacilniInstrument ADD CONSTRAINT FK_1DF2E9FAA420584D FOREIGN KEY (nacin_placina_id) REFERENCES NacinPlacina (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE PostavkaRacuna ADD CONSTRAINT FK_80B6F3595B3D808C FOREIGN KEY (racun_id) REFERENCES Racun (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ProdajaPredstave ADD CONSTRAINT FK_20D95C7FB31AE31 FOREIGN KEY (sedezni_red_id) REFERENCES SedezniRed (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ProdajaPredstave ADD CONSTRAINT FK_20D95C7FA81CCEF6 FOREIGN KEY (dogodek_id) REFERENCES Dogodek (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Racun ADD CONSTRAINT FK_B5B84F45BC902D3B FOREIGN KEY (kupec_id) REFERENCES Kupec (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Racun ADD CONSTRAINT FK_B5B84F45FE7B16E1 FOREIGN KEY (prodaja_predstave_id) REFERENCES ProdajaPredstave (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Racun ADD CONSTRAINT FK_B5B84F45A420584D FOREIGN KEY (nacin_placina_id) REFERENCES NacinPlacina (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Racun ADD CONSTRAINT FK_B5B84F4533341AB8 FOREIGN KEY (placilni_instrument_id) REFERENCES PlacilniInstrument (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE RazpisanSedez ADD CONSTRAINT FK_667E35D1F5E1D2D3 FOREIGN KEY (postavka_racuna_id) REFERENCES PostavkaRacuna (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE RazpisanSedez ADD CONSTRAINT FK_667E35D1C146C3F3 FOREIGN KEY (sedez_id) REFERENCES Sedez (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE RazpisanSedez ADD CONSTRAINT FK_667E35D1FE7B16E1 FOREIGN KEY (prodaja_predstave_id) REFERENCES ProdajaPredstave (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE RazpisanSedez ADD CONSTRAINT FK_667E35D117619010 FOREIGN KEY (rezervacija_id) REFERENCES Rezervacija (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Rezervacija ADD CONSTRAINT FK_48F1F62BFE7B16E1 FOREIGN KEY (prodaja_predstave_id) REFERENCES ProdajaPredstave (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Sedez ADD CONSTRAINT FK_52ED210BEF943358 FOREIGN KEY (vrsta_id) REFERENCES VrstaSedezev (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Sedez ADD CONSTRAINT FK_52ED210BB31AE31 FOREIGN KEY (sedezni_red_id) REFERENCES SedezniRed (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Sedez ADD CONSTRAINT FK_52ED210B1C0DC15A FOREIGN KEY (podrocja_sedenja_id) REFERENCES PodrocjeSedenja (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE VrstaSedezev ADD CONSTRAINT FK_7069C3C41C0DC15A FOREIGN KEY (podrocja_sedenja_id) REFERENCES PodrocjeSedenja (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Alternacija ADD CONSTRAINT FK_A4B7244F861BAED2 FOREIGN KEY (funkcija_id) REFERENCES Funkcija (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Alternacija ADD CONSTRAINT FK_A4B7244FA4976613 FOREIGN KEY (zaposlitev_id) REFERENCES Zaposlitev (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Alternacija ADD CONSTRAINT FK_A4B7244F10389148 FOREIGN KEY (oseba_id) REFERENCES Oseba (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Alternacija ADD CONSTRAINT FK_A4B7244F5BC4D310 FOREIGN KEY (pogodba_id) REFERENCES Pogodba (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Arhivalija ADD CONSTRAINT FK_BBFF8755A81CCEF6 FOREIGN KEY (dogodek_id) REFERENCES Dogodek (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Arhivalija ADD CONSTRAINT FK_BBFF875562B4FFCA FOREIGN KEY (uprizoritev_id) REFERENCES Uprizoritev (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Funkcija ADD CONSTRAINT FK_23AEB95862B4FFCA FOREIGN KEY (uprizoritev_id) REFERENCES Uprizoritev (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Funkcija ADD CONSTRAINT FK_23AEB958740EB038 FOREIGN KEY (alternacija_id) REFERENCES Alternacija (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Funkcija ADD CONSTRAINT FK_23AEB9586B361365 FOREIGN KEY (tipFunkcije_id) REFERENCES TipFunkcije (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Pogodba ADD CONSTRAINT FK_2DECFC5910389148 FOREIGN KEY (oseba_id) REFERENCES Oseba (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Pogodba ADD CONSTRAINT FK_2DECFC596BEEDE51 FOREIGN KEY (popa_id) REFERENCES popa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Pogodba ADD CONSTRAINT FK_2DECFC59FA5529EE FOREIGN KEY (trr_id) REFERENCES Trr (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Rekviziterstvo ADD CONSTRAINT FK_8198265413E60BC0 FOREIGN KEY (rekvizit_id) REFERENCES Rekvizit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Rekviziterstvo ADD CONSTRAINT FK_8198265462B4FFCA FOREIGN KEY (uprizoritev_id) REFERENCES Uprizoritev (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE StrosekUprizoritve ADD CONSTRAINT FK_11FFE6E062B4FFCA FOREIGN KEY (uprizoritev_id) REFERENCES Uprizoritev (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE StrosekUprizoritve ADD CONSTRAINT FK_11FFE6E06BEEDE51 FOREIGN KEY (popa_id) REFERENCES popa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Uprizoritev ADD CONSTRAINT FK_344A77A7C3B0D59 FOREIGN KEY (maticniOder_id) REFERENCES Prostor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Uprizoritev ADD CONSTRAINT FK_344A77AF35157B1 FOREIGN KEY (besedilo_id) REFERENCES Besedilo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Uprizoritev ADD CONSTRAINT FK_344A77A8E27EB8D FOREIGN KEY (zvrst_uprizoritve_id) REFERENCES ZvrstUprizoritve (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Uprizoritev ADD CONSTRAINT FK_344A77A3B262815 FOREIGN KEY (zvrst_surs_id) REFERENCES ZvrstSurs (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Uprizoritev ADD CONSTRAINT FK_344A77A853A965C FOREIGN KEY (producent_id) REFERENCES ProdukcijskaHisa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Zaposlitev ADD CONSTRAINT FK_B244904110389148 FOREIGN KEY (oseba_id) REFERENCES Oseba (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE DrugiVir ADD CONSTRAINT FK_E7D4CF2638C06EB FOREIGN KEY (enotaPrograma_id) REFERENCES EnotaPrograma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE EnotaPrograma ADD CONSTRAINT FK_8787A0E562B4FFCA FOREIGN KEY (uprizoritev_id) REFERENCES Uprizoritev (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE EnotaPrograma ADD CONSTRAINT FK_8787A0E57222D84B FOREIGN KEY (tipProgramskeEnote_id) REFERENCES TipProgramskeEnote (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE EnotaPrograma ADD CONSTRAINT FK_8787A0E5771EC7BD FOREIGN KEY (program_dela_id) REFERENCES ProgramDela (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE EnotaPrograma ADD CONSTRAINT FK_8787A0E55D0DA56C FOREIGN KEY (drzavaGostovanja_id) REFERENCES drza (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE EnotaPrograma ADD CONSTRAINT FK_8787A0E54AE1CD1C FOREIGN KEY (gostitelj_id) REFERENCES popa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ProdukcijaDelitev ADD CONSTRAINT FK_97AF082E38C06EB FOREIGN KEY (enotaPrograma_id) REFERENCES EnotaPrograma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ProdukcijaDelitev ADD CONSTRAINT FK_97AF082EC532925B FOREIGN KEY (koproducent_id) REFERENCES ProdukcijskaHisa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ProdukcijskaHisa ADD CONSTRAINT FK_E6FC20286BEEDE51 FOREIGN KEY (popa_id) REFERENCES popa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ProgramDela ADD CONSTRAINT FK_C81BC37F3A0E32E3 FOREIGN KEY (sezona_id) REFERENCES Sezona (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ProgramskaEnotaSklopa ADD CONSTRAINT FK_2D901816D6BC69D6 FOREIGN KEY (programRazno_id) REFERENCES EnotaPrograma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE StevilcenjeKonfig ADD CONSTRAINT FK_6054E804FF55F926 FOREIGN KEY (stevilcenje_id) REFERENCES Stevilcenje (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Datoteka ADD CONSTRAINT FK_781826C67E3C61F9 FOREIGN KEY (owner_id) REFERENCES uporabniki (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Mapa ADD CONSTRAINT FK_14A5D6D38A4A6C12 FOREIGN KEY (lastnik_id) REFERENCES uporabniki (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Mapa ADD CONSTRAINT FK_14A5D6D3727ACA70 FOREIGN KEY (parent_id) REFERENCES Mapa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mapa_zapis ADD CONSTRAINT FK_E9F8EE8257ED422F FOREIGN KEY (mapa_id) REFERENCES Mapa (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mapa_zapis ADD CONSTRAINT FK_E9F8EE82AF91ECD FOREIGN KEY (zapis_id) REFERENCES Zapis (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE MapaAcl ADD CONSTRAINT FK_7ADC957157ED422F FOREIGN KEY (mapa_id) REFERENCES Mapa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE MapaAcl ADD CONSTRAINT FK_7ADC9571FA6311EF FOREIGN KEY (perm_id) REFERENCES Permission (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Zapis ADD CONSTRAINT FK_1ED92829EF943358 FOREIGN KEY (vrsta_id) REFERENCES VrstaZapisa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Zapis ADD CONSTRAINT FK_1ED92829A54DBB1F FOREIGN KEY (datoteka_id) REFERENCES Datoteka (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Zapis ADD CONSTRAINT FK_1ED9282957ED422F FOREIGN KEY (mapa_id) REFERENCES Mapa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Zapis ADD CONSTRAINT FK_1ED92829253C4123 FOREIGN KEY (avtor_id) REFERENCES uporabniki (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Zapis ADD CONSTRAINT FK_1ED9282987FF3295 FOREIGN KEY (zaklenil_id) REFERENCES uporabniki (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ZapisLastnik ADD CONSTRAINT FK_2EAFF9DCAF91ECD FOREIGN KEY (zapis_id) REFERENCES Zapis (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE Permission2Role DROP CONSTRAINT FK_4FF23396FED90CCA');
        $this->addSql('ALTER TABLE MapaAcl DROP CONSTRAINT FK_7ADC9571FA6311EF');
        $this->addSql('ALTER TABLE Permission2Role DROP CONSTRAINT FK_4FF23396D60322AC');
        $this->addSql('ALTER TABLE Role2User DROP CONSTRAINT FK_704D3ABCD60322AC');
        $this->addSql('ALTER TABLE Role2User DROP CONSTRAINT FK_704D3ABCA76ED395');
        $this->addSql('ALTER TABLE OptionValue DROP CONSTRAINT FK_EF01221FA76ED395');
        $this->addSql('ALTER TABLE Oseba DROP CONSTRAINT FK_466966D7A76ED395');
        $this->addSql('ALTER TABLE Datoteka DROP CONSTRAINT FK_781826C67E3C61F9');
        $this->addSql('ALTER TABLE Mapa DROP CONSTRAINT FK_14A5D6D38A4A6C12');
        $this->addSql('ALTER TABLE Zapis DROP CONSTRAINT FK_1ED92829253C4123');
        $this->addSql('ALTER TABLE Zapis DROP CONSTRAINT FK_1ED9282987FF3295');
        $this->addSql('ALTER TABLE popa DROP CONSTRAINT FK_1C7ADBA5EE4B985A');
        $this->addSql('ALTER TABLE PostniNaslovi DROP CONSTRAINT FK_89C1F9D2EE4B985A');
        $this->addSql('ALTER TABLE Gostovanje DROP CONSTRAINT FK_CAE790C7EE4B985A');
        $this->addSql('ALTER TABLE EnotaPrograma DROP CONSTRAINT FK_8787A0E55D0DA56C');
        $this->addSql('ALTER TABLE OptionValue DROP CONSTRAINT FK_EF01221FA7C41D6F');
        $this->addSql('ALTER TABLE KontaktnaOseba DROP CONSTRAINT FK_2942B10710389148');
        $this->addSql('ALTER TABLE PostniNaslovi DROP CONSTRAINT FK_89C1F9D210389148');
        $this->addSql('ALTER TABLE Telefonska DROP CONSTRAINT FK_EF76E55910389148');
        $this->addSql('ALTER TABLE Trr DROP CONSTRAINT FK_37F6541A10389148');
        $this->addSql('ALTER TABLE TerminStoritve DROP CONSTRAINT FK_FEF7D84B10389148');
        $this->addSql('ALTER TABLE Alternacija DROP CONSTRAINT FK_A4B7244F10389148');
        $this->addSql('ALTER TABLE Pogodba DROP CONSTRAINT FK_2DECFC5910389148');
        $this->addSql('ALTER TABLE Zaposlitev DROP CONSTRAINT FK_B244904110389148');
        $this->addSql('ALTER TABLE KontaktnaOseba DROP CONSTRAINT FK_2942B1076BEEDE51');
        $this->addSql('ALTER TABLE PostniNaslovi DROP CONSTRAINT FK_89C1F9D2A233CB39');
        $this->addSql('ALTER TABLE Telefonska DROP CONSTRAINT FK_EF76E5596BEEDE51');
        $this->addSql('ALTER TABLE Trr DROP CONSTRAINT FK_37F6541A6BEEDE51');
        $this->addSql('ALTER TABLE Kupec DROP CONSTRAINT FK_2D2009BB6BEEDE51');
        $this->addSql('ALTER TABLE Pogodba DROP CONSTRAINT FK_2DECFC596BEEDE51');
        $this->addSql('ALTER TABLE StrosekUprizoritve DROP CONSTRAINT FK_11FFE6E06BEEDE51');
        $this->addSql('ALTER TABLE EnotaPrograma DROP CONSTRAINT FK_8787A0E54AE1CD1C');
        $this->addSql('ALTER TABLE ProdukcijskaHisa DROP CONSTRAINT FK_E6FC20286BEEDE51');
        $this->addSql('ALTER TABLE Oseba DROP CONSTRAINT FK_466966D769E8D4');
        $this->addSql('ALTER TABLE Pogodba DROP CONSTRAINT FK_2DECFC59FA5529EE');
        $this->addSql('ALTER TABLE TerminStoritve DROP CONSTRAINT FK_FEF7D84BA81CCEF6');
        $this->addSql('ALTER TABLE ProdajaPredstave DROP CONSTRAINT FK_20D95C7FA81CCEF6');
        $this->addSql('ALTER TABLE Arhivalija DROP CONSTRAINT FK_BBFF8755A81CCEF6');
        $this->addSql('ALTER TABLE Dogodek DROP CONSTRAINT FK_11E93B5D10398482');
        $this->addSql('ALTER TABLE Dogodek DROP CONSTRAINT FK_11E93B5DEF0F30B');
        $this->addSql('ALTER TABLE Predstava DROP CONSTRAINT FK_602F6E46EF0F30B');
        $this->addSql('ALTER TABLE Predstava DROP CONSTRAINT FK_602F6E466F7E7A33');
        $this->addSql('ALTER TABLE Dogodek DROP CONSTRAINT FK_11E93B5D5AC894AA');
        $this->addSql('ALTER TABLE Dogodek DROP CONSTRAINT FK_11E93B5D3A0E32E3');
        $this->addSql('ALTER TABLE ProgramDela DROP CONSTRAINT FK_C81BC37F3A0E32E3');
        $this->addSql('ALTER TABLE Dogodek DROP CONSTRAINT FK_11E93B5D18640538');
        $this->addSql('ALTER TABLE Dogodek DROP CONSTRAINT FK_11E93B5D14A6C237');
        $this->addSql('ALTER TABLE Racun DROP CONSTRAINT FK_B5B84F45BC902D3B');
        $this->addSql('ALTER TABLE PlacilniInstrument DROP CONSTRAINT FK_1DF2E9FAA420584D');
        $this->addSql('ALTER TABLE Racun DROP CONSTRAINT FK_B5B84F45A420584D');
        $this->addSql('ALTER TABLE Racun DROP CONSTRAINT FK_B5B84F4533341AB8');
        $this->addSql('ALTER TABLE Sedez DROP CONSTRAINT FK_52ED210B1C0DC15A');
        $this->addSql('ALTER TABLE VrstaSedezev DROP CONSTRAINT FK_7069C3C41C0DC15A');
        $this->addSql('ALTER TABLE RazpisanSedez DROP CONSTRAINT FK_667E35D1F5E1D2D3');
        $this->addSql('ALTER TABLE Racun DROP CONSTRAINT FK_B5B84F45FE7B16E1');
        $this->addSql('ALTER TABLE RazpisanSedez DROP CONSTRAINT FK_667E35D1FE7B16E1');
        $this->addSql('ALTER TABLE Rezervacija DROP CONSTRAINT FK_48F1F62BFE7B16E1');
        $this->addSql('ALTER TABLE Dogodek DROP CONSTRAINT FK_11E93B5DCC3AA562');
        $this->addSql('ALTER TABLE Uprizoritev DROP CONSTRAINT FK_344A77A7C3B0D59');
        $this->addSql('ALTER TABLE PostavkaRacuna DROP CONSTRAINT FK_80B6F3595B3D808C');
        $this->addSql('ALTER TABLE RazpisanSedez DROP CONSTRAINT FK_667E35D117619010');
        $this->addSql('ALTER TABLE RazpisanSedez DROP CONSTRAINT FK_667E35D1C146C3F3');
        $this->addSql('ALTER TABLE ProdajaPredstave DROP CONSTRAINT FK_20D95C7FB31AE31');
        $this->addSql('ALTER TABLE Sedez DROP CONSTRAINT FK_52ED210BB31AE31');
        $this->addSql('ALTER TABLE Sedez DROP CONSTRAINT FK_52ED210BEF943358');
        $this->addSql('ALTER TABLE TerminStoritve DROP CONSTRAINT FK_FEF7D84B740EB038');
        $this->addSql('ALTER TABLE Funkcija DROP CONSTRAINT FK_23AEB958740EB038');
        $this->addSql('ALTER TABLE Uprizoritev DROP CONSTRAINT FK_344A77AF35157B1');
        $this->addSql('ALTER TABLE Alternacija DROP CONSTRAINT FK_A4B7244F861BAED2');
        $this->addSql('ALTER TABLE Alternacija DROP CONSTRAINT FK_A4B7244F5BC4D310');
        $this->addSql('ALTER TABLE Rekviziterstvo DROP CONSTRAINT FK_8198265413E60BC0');
        $this->addSql('ALTER TABLE Funkcija DROP CONSTRAINT FK_23AEB9586B361365');
        $this->addSql('ALTER TABLE Gostujoca DROP CONSTRAINT FK_4A45D07962B4FFCA');
        $this->addSql('ALTER TABLE Predstava DROP CONSTRAINT FK_602F6E4662B4FFCA');
        $this->addSql('ALTER TABLE Vaja DROP CONSTRAINT FK_2390FC9662B4FFCA');
        $this->addSql('ALTER TABLE Arhivalija DROP CONSTRAINT FK_BBFF875562B4FFCA');
        $this->addSql('ALTER TABLE Funkcija DROP CONSTRAINT FK_23AEB95862B4FFCA');
        $this->addSql('ALTER TABLE Rekviziterstvo DROP CONSTRAINT FK_8198265462B4FFCA');
        $this->addSql('ALTER TABLE StrosekUprizoritve DROP CONSTRAINT FK_11FFE6E062B4FFCA');
        $this->addSql('ALTER TABLE EnotaPrograma DROP CONSTRAINT FK_8787A0E562B4FFCA');
        $this->addSql('ALTER TABLE Alternacija DROP CONSTRAINT FK_A4B7244FA4976613');
        $this->addSql('ALTER TABLE Uprizoritev DROP CONSTRAINT FK_344A77A3B262815');
        $this->addSql('ALTER TABLE Uprizoritev DROP CONSTRAINT FK_344A77A8E27EB8D');
        $this->addSql('ALTER TABLE DrugiVir DROP CONSTRAINT FK_E7D4CF2638C06EB');
        $this->addSql('ALTER TABLE ProdukcijaDelitev DROP CONSTRAINT FK_97AF082E38C06EB');
        $this->addSql('ALTER TABLE ProgramskaEnotaSklopa DROP CONSTRAINT FK_2D901816D6BC69D6');
        $this->addSql('ALTER TABLE Uprizoritev DROP CONSTRAINT FK_344A77A853A965C');
        $this->addSql('ALTER TABLE ProdukcijaDelitev DROP CONSTRAINT FK_97AF082EC532925B');
        $this->addSql('ALTER TABLE EnotaPrograma DROP CONSTRAINT FK_8787A0E5771EC7BD');
        $this->addSql('ALTER TABLE EnotaPrograma DROP CONSTRAINT FK_8787A0E57222D84B');
        $this->addSql('ALTER TABLE StevilcenjeKonfig DROP CONSTRAINT FK_6054E804FF55F926');
        $this->addSql('ALTER TABLE Zapis DROP CONSTRAINT FK_1ED92829A54DBB1F');
        $this->addSql('ALTER TABLE Mapa DROP CONSTRAINT FK_14A5D6D3727ACA70');
        $this->addSql('ALTER TABLE mapa_zapis DROP CONSTRAINT FK_E9F8EE8257ED422F');
        $this->addSql('ALTER TABLE MapaAcl DROP CONSTRAINT FK_7ADC957157ED422F');
        $this->addSql('ALTER TABLE Zapis DROP CONSTRAINT FK_1ED9282957ED422F');
        $this->addSql('ALTER TABLE Zapis DROP CONSTRAINT FK_1ED92829EF943358');
        $this->addSql('ALTER TABLE mapa_zapis DROP CONSTRAINT FK_E9F8EE82AF91ECD');
        $this->addSql('ALTER TABLE ZapisLastnik DROP CONSTRAINT FK_2EAFF9DCAF91ECD');
        $this->addSql('DROP TABLE Permission');
        $this->addSql('DROP TABLE revizije');
        $this->addSql('DROP TABLE Role');
        $this->addSql('DROP TABLE Permission2Role');
        $this->addSql('DROP TABLE uporabniki');
        $this->addSql('DROP TABLE Role2User');
        $this->addSql('DROP TABLE Abonma');
        $this->addSql('DROP TABLE drza');
        $this->addSql('DROP TABLE KontaktnaOseba');
        $this->addSql('DROP TABLE Option');
        $this->addSql('DROP TABLE OptionValue');
        $this->addSql('DROP TABLE Oseba');
        $this->addSql('DROP TABLE popa');
        $this->addSql('DROP TABLE Posta');
        $this->addSql('DROP TABLE PostniNaslovi');
        $this->addSql('DROP TABLE Telefonska');
        $this->addSql('DROP TABLE Trr');
        $this->addSql('DROP TABLE Dogodek');
        $this->addSql('DROP TABLE DogodekIzven');
        $this->addSql('DROP TABLE Gostovanje');
        $this->addSql('DROP TABLE Gostujoca');
        $this->addSql('DROP TABLE Predstava');
        $this->addSql('DROP TABLE Sezona');
        $this->addSql('DROP TABLE Vaja');
        $this->addSql('DROP TABLE Zasedenost');
        $this->addSql('DROP TABLE TerminStoritve');
        $this->addSql('DROP TABLE Kupec');
        $this->addSql('DROP TABLE NacinPlacina');
        $this->addSql('DROP TABLE PlacilniInstrument');
        $this->addSql('DROP TABLE PodrocjeSedenja');
        $this->addSql('DROP TABLE PostavkaRacuna');
        $this->addSql('DROP TABLE ProdajaPredstave');
        $this->addSql('DROP TABLE Prostor');
        $this->addSql('DROP TABLE Racun');
        $this->addSql('DROP TABLE RazpisanSedez');
        $this->addSql('DROP TABLE Rezervacija');
        $this->addSql('DROP TABLE Sedez');
        $this->addSql('DROP TABLE SedezniRed');
        $this->addSql('DROP TABLE VrstaSedezev');
        $this->addSql('DROP TABLE Alternacija');
        $this->addSql('DROP TABLE Arhivalija');
        $this->addSql('DROP TABLE Besedilo');
        $this->addSql('DROP TABLE Funkcija');
        $this->addSql('DROP TABLE Pogodba');
        $this->addSql('DROP TABLE Rekvizit');
        $this->addSql('DROP TABLE Rekviziterstvo');
        $this->addSql('DROP TABLE StrosekUprizoritve');
        $this->addSql('DROP TABLE TipFunkcije');
        $this->addSql('DROP TABLE Uprizoritev');
        $this->addSql('DROP TABLE Zaposlitev');
        $this->addSql('DROP TABLE ZvrstSurs');
        $this->addSql('DROP TABLE ZvrstUprizoritve');
        $this->addSql('DROP TABLE DrugiVir');
        $this->addSql('DROP TABLE EnotaPrograma');
        $this->addSql('DROP TABLE ProdukcijaDelitev');
        $this->addSql('DROP TABLE ProdukcijskaHisa');
        $this->addSql('DROP TABLE ProgramDela');
        $this->addSql('DROP TABLE ProgramskaEnotaSklopa');
        $this->addSql('DROP TABLE TipProgramskeEnote');
        $this->addSql('DROP TABLE Stevilcenje');
        $this->addSql('DROP TABLE StevilcenjeKonfig');
        $this->addSql('DROP TABLE StevilcenjeStanje');
        $this->addSql('DROP TABLE Datoteka');
        $this->addSql('DROP TABLE Mapa');
        $this->addSql('DROP TABLE mapa_zapis');
        $this->addSql('DROP TABLE MapaAcl');
        $this->addSql('DROP TABLE VrstaZapisa');
        $this->addSql('DROP TABLE Zapis');
        $this->addSql('DROP TABLE ZapisLastnik');
    }
}
