<!--
    Template za izpis seznamov
    Inputs:
        $title      - naslov izpisa
        $date       - datum izpisa
        $entities   - seznam entitet sortiranih po diskriminatorju
        $table      - definicija Table
-->
<!DOCTYPE html>
<html>
    <head>
        <title><?= isset($title) ? $title : '' ?></title>
        <meta charset="UTF-8">
        <style type="text/css">
            @page {

                size: <?= $this->pageSize ? : 'A4 portrait' ?>;
                margin: 1cm;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                font-size: 9px;

                @top-left {
                    content: "<?= $firma->getNaziv() ?>";
                };

                @top-center {
                    font-size: 12px;
                    font-weight: bold;
                    content: "<?= isset($title) ? $title : '' ?>";
                };

                @top-right {
                    content: "<?= $this->translate("Stran:", 'default') ?> " counter(page) " / " counter(pages);
                };

                @bottom-left {
                    content: "max.si";
                };

                @bottom-right {
                    content: "<?= isset($date) ? $date->format('d.m.Y') : '' ?>";
                };
            }
            <?= $this->partial('printlayout/style', get_defined_vars()); ?>
        </style>
    </head>
    <body>
        <?php 
        echo $this->table($table, $entities); 
        ?>
    </body>
</html>