## YAML Template.
---
type: rest
entityClass: Koledar\Entity\TipVaje
forms:
    default: 
        elements:
#            - id
            - name: sifra
              options: 
                  required: false                  
            - ime
            - opis
#            - vaje
lists:
    default: 
        filter:
            elements: 
                - name: q
                  type: text
                  options:
                    required: false
                    placeholder: Išči..
                    label: Išči
        hydrator:
            - exclude: []
#    vse: 
#        filter:
    