## YAML Template.
---
type: rest
entityClass: Koledar\Entity\Predstava
forms:
    default: 
        elements:
#            - id
            - dogodek
            - uprizoritev
            - gostovanje           
lists:
    default: 
        filter:
            elements:                 
                - name: uprizoritev
                  type: toone
                  options:
                      label: Uprizoritev
                      targetEntity: Produkcija\Entity\Uprizoritev
                      required: true
        hydrator:
            byValue:
                - dogodek
#    vse: 
#        filter: