## YAML Template.
---
type: rest
entityClass: Koledar\Entity\Predstava
forms:
    default: 
        elements:
#            - id
#            - dogodek
            - zaporedna
            - zaporednaSez
            - uprizoritev
            - gostovanje
            - objavljenZacetek
            - dezurni
            - name: title
              type: text
              options:
                  label: Naslov dogodka
                  required: true
            - name: status
              type: select
              options:
                  label: Status
                  reqired: true
                  value_options: @dogodek.status
            - name: zacetek
              type: datetime
              options: 
                  label: Začetek
                  required: false
            - name: konec
              type: datetime
              options: 
                  label: Konec
                  required: false
#                                   če je gostovanje, ne potrebujemo prostora
            - name: prostor
              type: toone
              options:
                  targetEntity: Prodaja\Entity\Prostor
                  label: Prostor
                  required: false
            - name: sezona
              type: toone
              options:
                  targetEntity: Koledar\Entity\Sezona
                  label: Sezona
                  required: false
        hydrator:
            byValue:
                - dogodek
            lookups:
                - dogodek.prostor
            virtual:
                - name: zacetek
                  type: datetime
                - name: konec
                  type: datetime
                - name: prostor
                  type: byRef
                  targetEntity: Prodaja\Entity\Prostor
                - name: sezona
                  type: byRef
                  targetEntity: Koledar\Entity\Sezona
                - title
                - status                  
lists:
    default: 
        filter:
            elements:                 
                - name: uprizoritev
                  type: toone
                  options:
                      label: Uprizoritev
                      targetEntity: Produkcija\Entity\Uprizoritev
                      required: true
        hydrator:
            byValue:
                - dogodek
            virtual:
                - name: zacetek
                  type: datetime
                - name: konec
                  type: datetime
#    vse: 
#        filter:
relation:
    default:
        abonmaji:
            enabled: true
            hydrator:
                exclude: []
                