## YAML Template.
---
type: rest
entityClass: Koledar\Entity\Predstava
forms:
    default: 
        elements:
#            - id
#            - dogodek
            - zaporedna
            - porocilo
            - uprizoritev
            - gostovanje
            - objavljenZacetek
            - name: title
              type: text
              options:
                  label: Naslov dogodka
                  required: true
            - name: status
              type: select
              options:
                  label: Status
                  reqired: true
                  value_options: @dogodek.status
            - name: zacetek
              type: datetime
              options: 
                  label: Začetek
                  required: false
            - name: konec
              type: datetime
              options: 
                  label: Konec
                  required: false
        hydrator:
            byValue:
                - dogodek
            virtual:
                - name: zacetek
                  type: datetime
                - name: konec
                  type: datetime

lists:
    default: 
        filter:
            elements:                 
                - name: uprizoritev
                  type: toone
                  options:
                      label: Uprizoritev
                      targetEntity: Produkcija\Entity\Uprizoritev
                      required: true
        hydrator:
            byValue:
                - dogodek
            virtual:
                - name: zacetek
                  type: datetime
                - name: konec
                  type: datetime
#    vse: 
#        filter: