## YAML Template.
---
type: rest
entityClass: Koledar\Entity\Predstava
forms:
    default: 
        elements:
#            - id
#            - dogodek
            - zaporedna
            - porocilo
            - uprizoritev
            - gostovanje 
            - name: zacetek
              type: datetime
              options: 
                  label: Začetek
                  required: false
            - name: konec
              type: datetime
              options: 
                  label: Konec
                  required: false
        hydrator:
            byValue:
                - dogodek
            virtual:
                - zacetek
                - konec
    uprizoritev: 
        elements:
            - uprizoritev
            - name: zacetek
              type: datetime
              options: 
                  label: Začetek
                  required: false
            - name: konec
              type: datetime
              options: 
                  label: Konec
                  required: false
        hydrator:
            byValue:
                - dogodek
            virtual:
                - zacetek
                - konec
lists:
    default: 
        filter:
            elements:                 
                - name: uprizoritev
                  type: toone
                  options:
                      label: Uprizoritev
                      targetEntity: Produkcija\Entity\Uprizoritev
                      required: true
        hydrator:
            byValue:
                - dogodek
            virtual:
                - zacetek
                - konec
#    vse: 
#        filter: