## YAML Template.
---
type: rest
entityClass: Koledar\Entity\DogodekSplosni
forms:
    default: 
        elements:
#            - id
            - dogodek
        
lists:
    default: 
        filter:
        hydrator:
            - exclude: []
#    vse: 
#        filter:
    
hydrator: 
    byValue: [dogodek]