## YAML Template.
---
type: rest
entityClass: ProgramDela\Entity\TipProgramskeEnote
forms:
    default: 
        elements:
#            - id
            - sifra
            - naziv
            - koprodukcija
            - maxFaktor
            - maxVsi
#            - enotaPrograma
lists:
    default: 
        hydrator:
            - exclude: []
#    vse: 
#        hydrator:
#            - exclude: []
relation:
    default:
        enotePrograma:
            enabled: true
            hydrator:
                exclude: []    
            