## YAML Template.
---
#       module/App/config/rest.postninaslov.yml
type: rest
entityClass: ProgramDela\Entity\EnotaPrograma
forms:
    default: 
        elements:
#            - id
            - celotnaVrednost
            - zaproseno
            - lastnaSredstva
            - avtorskiHonorarji
            - tantieme
            - drugiViri
            - drugiJavni
            - obiskDoma
            - obiskGost
            - obiskZamejo
            - obiskInt
            - ponoviDoma
            - ponoviZamejo
            - ponoviGost
            - ponoviInt
            - utemeljitev
            - uprizoritev
            - tipProgramskeEnote
            - tip
lists:
    default: 
        hydrator:
            - exclude: []