## YAML Template.
---
entityClass: Aaa\Entity\Permission
disabledMethods: 
    - delete
permPrefix: User    
forms:
    default: 
        disabledMethods:
            - update
            - read
    extra:
        disabledMethods:
            - create
            - read
            
            