## YAML Template.
---
entityClass: Aaa\Entity\Permission
permPrefix: Aaa
disabledMethods: 
forms:
    default:
        elements:
            - description
            - name
    extra:
        disabledMethods:
            - create
            - read
lists:
    default:
hydrator:
    exclude: 
relation:
    default:
        roles:
            enabled: true
            hydrator:
                exclude: [permissions]
