## YAML Template.
---
entityClass: Aaa\Entity\Permission
permPrefix: Aaa
disabledMethods: 
    - delete
    - create
    - update
forms:
    default:
        disabledMethods:
            - update
    extra:
        disabledMethods:
            - create
            - read
lists:
    default:
hydrator:
    exclude: 
        - builtIn
