## YAML Template.
---
entityClass: Aaa\Entity\Permission
permPrefix: Aaa
disabledMethods: 
forms:
    default:
        elements:
            - description
            - name
    extra:
        disabledMethods:
            - create
            - read
lists:
    default:
        filter: 
            elements: 
                - name: q
                  type: text
                  options:
                    required: false
                    placeholder: Išči..
                    label: Išči
hydrator:
    exclude: 
relation:
    default:
        roles:
            enabled: true
            hydrator:
                exclude: [permissions]
