<?php

if (isset($this->reason) && $this->reason) {
    $reasonMessage = '';
    switch ($this->reason) {
        case 'error-controller-cannot-dispatch':
            $reasonMessage = $this->translate('The requested controller was unable to dispatch the request.');
            break;
        case 'error-controller-not-found':
            $reasonMessage = $this->translate('The requested controller could not be mapped to an existing controller class.');
            break;
        case 'error-controller-invalid':
            $reasonMessage = $this->translate('The requested controller was not dispatchable.');
            break;
        case 'error-router-no-match':
            $reasonMessage = $this->translate('The requested URL could not be matched by routing.');
            break;
        case 'Objekt ne obstaja.':
            $reasonMessage = $This->translate('Objekta ni mogoče najti.');
            break;

        default:
            $reasonMessage = $this->translate('We cannot determine at this time why a 404 was generated.');
            break;
    }

    $error = [
        'success' => false,
        'errors'  => [
            [
                'code'    => 404,
                'message' => $reasonMessage
            ]
        ]
    ];

    if (isset($this->controller) && $this->controller) {

        if (isset($this->controller_class) && $this->controller_class && $this->controller_class != $this->controller) {
            $error['controllerClass'] = sprintf($this->translate('resolves to %s'), $this->escapeHtml($this->controller_class));
        }

        $error['controller'] = $this->escapeHtml($this->controller);
    }
}
header('Content-type: application/json; charset=UTF-8');
echo \Zend\Json\Json::encode($error);
