<?php

header('Content-type: application/json; charset=UTF-8');
if ($this->exception instanceof \Max\Exception\ApiDisabledException) {
    echo Zend\Json\Json::encode(["success" => false, "errors"  => [
            [
                "message" => $this->exception->getMessage(),
                "code"    => 404
            ]
        ]
    ]);
    return;
}

$error = [
    'success' => false,
    'errors'  => [[
    'message' => $this->exception->getMessage(),
    'code'    => $this->exception->getCode(),
    'file'    => $this->exception->getFile(),
    'line'    => $this->exception->getLine(),
    'trace'   => explode("\n", $this->exception->getTraceAsString())
        ]],
    'prev'    => []
];

function formatDebug(&$err, Exception $exception)
{
    $err['errors'][] = [
        'type'    => get_class($exception),
        'message' => $exception->getMessage(),
        'file'    => $exception->getFile(),
        'line'    => $exception->getLine()
    ];
    $e = $exception->getPrevious();
    if ($e) {
        formatDebug($err, $e);
    }
}

if ($exception->getPrevious()) {
    formatDebug($error, $exception->getPrevious());
}
echo \Zend\Json\Json::encode($error);

