<?php
/**
 * tmpl za festivale
 *  programski sklop 2 - zavihek 2
 * 
 * User: Alesch
 * Date: 21.9.2015
 * 
 * 
 * @param \ProgramDela\Entity\ProgramPremiera $model  
 */
// 

$drugiViri       = $model->getDrugiViri();
$kop             = $model->getKoprodukcije();
$imakop          = $model->getImaKoprodukcije();
$stDogodkov      = $model->getStPredstav() + 
        $model->getStOkroglihMiz() +
        $model->getStPredstavitev() + 
        $model->getStDelavnic() + 
        $model->getStDrugiDogodki();
?>
<div id="festivali">
    <h2>Uprizoritvena umetnost – Programski sklop II</h2>
    <h2>Festivali</h2>
    <table>
        <tr class="suma-row">
            <td>Naziv festivala:</td>
            <td class="right-align"><strong><?= $model->getNaziv() ?></strong></td>
        </tr>
        <tr>
            <td>Zvrst festivala:</td>
            <td class="right-align"><?= $model->getZvrst() ?></td>
        </tr>
        <tr>
            <td>Skupno število dogodkov v okviru festivala:</td>
            <td class="cell-type-number"><?= $stDogodkov ?></td>
        </tr>
        <tr>
            <td class="alineja">predstav:</td>
            <td class="cell-type-date"><?= $model->getStPredstav() ?></td>
        </tr>
        <tr>
            <td class="alineja">okroglih miz:</td>
            <td class="cell-type-number"><?= $model->getStOkroglihMiz() ?></td>
        </tr>       
        <tr>
            <td class="alineja">predstavitev:</td>
            <td class="cell-type-number"><?= $model->getStPredstavitev() ?></td>
        </tr>       
        <tr>
            <td class="alineja">delavnic:</td>
            <td class="cell-type-number"><?= $model->getStDelavnic() ?></td>
        </tr>
        <tr>
            <td class="alineja">drugih dogodkov:</td>
            <td class="cell-type-number"><?= $model->getStDrugiDogodki() ?></td>
        </tr>
        <tr>
            <td>Skupno število festivalskih produkcij:</td>
            <td class="cell-type-number"><?= $model->getStProdukcij() ?></td>
        </tr>
        <tr>
            <td>Pričakovano število obiskovalcev:</td>
            <td class="cell-type-number"><?= $model->getObiskDoma() ?></td>
        </tr>
        <tr>
            <td>Čas priprave festivala:</td>
            <td class="cell-type-number"><?= $model->getCasPriprave() ?></td>
        </tr>
        <tr>
            <td>Čas izvedbe festivala:</td>
            <td class="cell-type-number"><?= $model->getCasIzvedbe() ?></td>
        </tr>
        <tr>
            <td>Prizorišče(šča):</td>
            <td class="cell-type-number"><?= $model->getPrizorisca() ?></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Umetniški vodja festivala:</td>
            <td class="right-align"><?= $model->getUmetvodja() ?></td>
        </tr>
        <tr>
            <td>Programsko telo festivala:</td>
            <td class="right-align"><?= $model->getProgramskoTelo() ?></td>
        </tr>
        <?php if($imakop) { ?>
            <tr>
                <td>Soorganizatorji:</td>
                <td></td>
            </tr>
            <?php 
                echo $this->partial('koproducenti', array('kop' => $kop)); 
            ?>
        <?php } ?>

        <tr>
            <td>Predvideno št. tujih selektorjev - gostov:</td>
            <td class="cell-type-number"><?= $model->getStTujihSelektorjev() ?></td>
        </tr>
        <tr>
            <td>Št. zaposlenih, ki sodelujejo pri izvedbi festivala:</td>
            <td class="cell-type-number"><?= $model->getStZaposlenih() ?></td>
        </tr>
        <tr>
            <td>Št. vseh, ki sodelujejo honorarno pri izvedbi festivala in jim honorar izplačuje javni zavod:</td>
            <td class="cell-type-number"><?= $model->getStHonorarnih() ?></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Zaprošena sredstva Ministrstva za kulturo:</td>
            <td class="cell-type-number"><?= number_format($model->getZaproseno(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Lastna sredstva:</td>
            <td class="cell-type-number"><?= number_format($model->getLastnaSredstva(), 2, ',', '.') ?></td>
        </tr>
        <?php if ($drugiViri) { ?>
            <tr class="suma-row">
                <td>Drugi Viri:</td>
                <td class="cell-type-number"><?= number_format($model->vsotaDrugihVirov(), 2, ',', '.') ?> </td>
            </tr>        
            <?php
            $this->partialLoop()->setObjectKey('drugiViri');
            echo $this->partialLoop('drugiViri.phtml', $drugiViri); ?>
            <tr>
                <td>&nbsp;</td>
                <td></td>
            </tr>
        <?php } ?>
        <tr>
            <td>Vir druga ministrstva in lokalna skupnost:</td>
            <td class="cell-type-number"><?= number_format($model->getDrugiJavni(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Celotna vrednost festivala:</td>
            <td class="cell-type-number"><?= number_format($model->getCelotnaVrednost(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td><h2>Vsebinska utemeljitev predloga:</h2></td>
            <td></td>
        </tr>
    </table>
</div>