<?php
/**
 * tmpl za gostujoče 
 * User: Alesch
 * Date: 21.9.2015
 */
// 
$upr             = $model->getUprizoritev();
$drugiViri       = $model->getDrugiViri();

// iz gostovanja
$zaprSredstva    = number_format($model->zaproseno, 2, ',', '.');
$lastSredstva    = number_format($model->lastnaSredstva, 2, ',', '.');
$drugSredstva    = number_format($model->drugiJavni, 2, ',', '.');
$obiskDoma       = number_format($model->obiskDoma, 0, ',', '.');
$stPredstav      = number_format($model->ponoviDoma, 0, ',', '.');
$celotnaVred     = number_format($model->celotnaVrednost, 2, ',', '.');

?>
<div id="gostujoce">
    <h2>Gostujoče uprizoritve - iz Slovenije, zamejstva in tujine</h2>
    <table>
        <?php
            $this->partial()->setObjectKey('upr');
            echo $this->partial('uprizoritev', $upr);
        ?>
        <tr>
            <td>Število predstav:</td>
            <td class="cell-type-number"><?= $stPredstav ?></td>
        </tr>       
        <tr>
            <td>Načrtovano št. vseh obiskovalcev:</td>
            <td class="cell-type-number"><?= $obiskDoma ?></td>
        </tr>
        <tr>
            <td>Zaprošena sredstva Ministrstva za kulturo:</td>
            <td class="cell-type-number"><?= $zaprSredstva ?></td>
        </tr>
        <tr>
            <td>Lastna sredstva:</td>
            <td class="cell-type-number"><?= $lastSredstva ?></td>
        </tr>

        <?php if ($drugiViri) { ?>
            <tr class="suma-row">
                <td>Drugi Viri:</td>
                <td class="cell-type-number"><?= number_format($model->vsotaDrugihVirov(), 2, ',', '.') ?> </td>
            </tr>        
            <?php
            $this->partialLoop()->setObjectKey('drugiViri');
            echo $this->partialLoop('drugiViri.phtml', $drugiViri); ?>
            <tr>
                <td>&nbsp;</td>
                <td></td>
            </tr>
        <?php } ?>

        <tr>
            <td>Vir druga ministrstva in lokalna skupnost:</td>
            <td class="cell-type-number"><?= $drugSredstva ?></td>
        </tr>
        <tr>
            <td>Celotna vrednost gostovanja:</td>
            <td class="cell-type-number"><?= $celotnaVred ?></td>
        </tr>
    </table>
    <h2>Vsebinska utemeljitev predloga:</h2>
</div>

