<?php
/**
 * tmpl za gostujoče 
 * User: Alesch
 * Date: 21.9.2015
 */
// 
$upr              = $model->getUprizoritev();
$drugiViri        = $model->getDrugiViri();
$kop              = $model->getKoprodukcije();
$imakop           = $model->getImaKoprodukcije();

?>
<div id="gostujoce">
    <h2>Uprizoritvena umetnost – Programski sklop I</h2>
    <h2>Gostujoče uprizoritve - iz Slovenije, zamejstva in tujine</h2>
    <table>
        <?php
            $this->partial()->setObjectKey('upr');
            echo $this->partial('uprizoritev', $upr);
        ?>
        <tr>
            <td>Število predstav:</td>
            <td></td>
            <td class="cell-type-number"><?= number_format($model->getPonoviDoma(), 0, ',', '.') ?></td>
        </tr>       
        <tr>
            <td>Načrtovano št. vseh obiskovalcev:</td>
            <td></td>
            <td class="cell-type-number"><?= number_format($model->getObiskDoma(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <?php if ($imakop) { ?>
            <tr class="suma-row">
                <td>Koproducenti:</td>
                <td class="cell-type-number">Koeficient</td>
                <td class="cell-type-number">Delež</td>
            </tr>
            <?php
                $this->partial()->setObjectKey('kop');
                echo $this->partial('koproducenti', $kop);
            ?>
        <?php } ?>
        <tr>
            <td>Zaprošena sredstva Ministrstva za kulturo:</td>
            <td></td>
            <td class="cell-type-number"><?= number_format($model->getZaproseno(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Lastna sredstva:</td>
            <td></td>
            <td class="cell-type-number"><?= number_format($model->getLastnaSredstva(), 2, ',', '.') ?></td>
        </tr>

        <?php if ($drugiViri) { ?>
            <tr class="suma-row">
                <td>Drugi Viri:</td>
                <td></td>
                <td class="cell-type-number"><?= number_format($model->vsotaDrugihVirov(), 2, ',', '.') ?> </td>
            </tr>        
            <?php
            $this->partialLoop()->setObjectKey('drugiViri');
            echo $this->partialLoop('drugiViri.phtml', $drugiViri); ?>
            <tr>
                <td>&nbsp;</td>
                <td></td>
                <td></td>
            </tr>
        <?php } ?>

        <tr>
            <td>Vir druga ministrstva in lokalna skupnost:</td>
            <td></td>
            <td class="cell-type-number"><?= number_format($model->getDrugiJavni(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Celotna vrednost gostovanja:</td>
            <td></td>
            <td class="cell-type-number"><?= number_format($model->getCelotnaVrednost(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega stroški matičnega javnega zavoda:</td>
            <td></td>
            <td class="cell-type-number"><?= number_format($model->getNasDelez(), 2, ',', '.') ?></td>
        </tr>
        
    </table>
    <h2>Vsebinska utemeljitev predloga:</h2>
</div>

