<?php
$tr = $this->plugin('translate')->getTranslator();
if (method_exists($model, 'getJezik')) {
    $tr->setLocale($model->getJezik());
}

$tm             = !empty($this->margins[0]) ? $this->margins[0] : 17;
$lm             = !empty($this->margins[1]) ? $this->margins[1] : 15;
$bm             = !empty($this->margins[2]) ? $this->margins[2] : 17;
$rm             = !empty($this->margins[3]) ? $this->margins[3] : 15;
$pagesize       = $this->pageSize ? $this->pagesize : 'a4';
$orientation    = $this->orientation ? $this->orientation : 'p';
$isheaderfooter = $this->ishf;
$firmanaziv     = $this->firma ? $this->firma->getNaziv() : '';

if (is_array($this->title)) {
    $naslov = !empty($this->title[0]) ? $this->translate($this->title[0]) . ' ' . $this->title[1] : '';
} else {
    $naslov = $this->title;
}
?>
<!DOCTYPE html>
<html>
    <head>
        <title><?= $naslov ?></title>
        <meta charset="UTF-8">
        <style type="text/css">

            @page lezeca {
                sheet-size: A4-L;
                odd-header-name: docHeader;
                even-header-name: docHeader;
                odd-footer-name: docFooter;
                even-footer-name: docFooter;
            }
            @page pokoncna {
                sheet-size: A4-P;
                odd-header-name: docHeader;
                even-header-name: docHeader;
                odd-footer-name: docFooter;
                even-footer-name: docFooter;
            }
            @page lezeca-noheader {
                sheet-size: A4-L;
                odd-header-name: _blank;
                even-header-name: _blank;
                odd-footer-name: _blank;
                even-footer-name: _blank;
            }
            @page :first {
                sheet-size: <?= $pagesize . '-' . $orientation ?>;
                size: auto;
                margin-top: <?= $tm ?>mm ;
                margin-left: <?= $lm ?>mm ;
                margin-bottom: <?= $bm ?>mm ;
                margin-right: <?= $rm ?>mm ;
                margin-footer: 5mm;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                font-size: 10px;
            }
            @media screen {
                #docHeader, #docFooter {
                    display: none;
                }
            }

            <?= $_css ? $this->partial($_css) : '' ?>

            #kazalniki {
                page: lezeca-noheader;   
                page-break-after: avoid;
            }
            #naslovnica {
                page-break-before: left;
                page: pokoncna;        
            }
            #premiere {
                page-break-before: always;
                page: pokoncna;        
            }
            #ponovitve-premier {
                page-break-before: always;
                page: pokoncna;        
            }
            #ponovitve-prej {
                page-break-before: always;
                page: pokoncna;        
            }
            #gostujoce {
                page-break-before: always;
                page: pokoncna;        
            }
            #mednarodna {
                page-break-before: always;
                page: pokoncna;        
            }
            #festivali {
                page-break-before: always;      
                page: pokoncna;        
            }
            #razno {
                page-break-before: always;
                page: pokoncna;        
            }
            #izjemni-dogodki {
                page-break-before: always;
                page: pokoncna;        
            }
            #kazalniki-priloga {
                page: pokoncna;        
            }
            #postavke-c2 {
                page: lezeca;
            }

        </style>
    </head>
    <body>
        <?php if ($isheaderfooter) { ?>
        <htmlpageheader name="docHeader" id="docHeader" style="display:none">
            <table width="100%"
                   style="topntail: 0; border-bottom: 1px solid #000000; vertical-align: bottom; font-weight: bold;">
                <tr>
                    <td width="33%"><?= isset($firmanaziv) ? $firmanaziv : '' ?></td>
                    <td width="33%"></td>
                    <td width="33%" style="text-align: right; font-style: italic;"><?= $naslov ?></td>
                </tr>
            </table>
        </htmlpageheader>
        <htmlpagefooter name="docFooter" id="docFooter" style="display:none">
            <table width="100%"
                   style="topntail: 0; border-top: 1px solid #000000; border-bottom: hidden; vertical-align: bottom; font-weight: bold; font-style: italic;"
                   class="nobottomborder">
                <tr>
                    <td style="border-bottom: 1px solid #fff;" width="33%">{DATE j.m.Y}</td>
                    <td style="border-bottom: 1px solid #fff;" width="33%"></td>
                    <td style="border-bottom: 1px solid #fff; text-align: right;" width="33%"><?= $this->translate('Stran') ?>: {PAGENO}/{nbpg}</td>
                </tr>
            </table>
        </htmlpagefooter>
        <?php } ?>
