<?php
$povprecnoObisk = ($model->getStIzvPonPrem() + $model->getStIzvPrem() != 0) ?
        ($model->getStObiskPonPrem() + $model->getStObiskPrem()) / ($model->getStIzvPonPrem() + $model->getStIzvPrem()) : 0
?>

<div id ='kazalniki-priloga'>
    <h1>Kazalniki priloga 2</h1>
    <table>
        <tr>
            <td class="cell-type-header-title">Kazalniki</td>
            <td class="cell-type-header-title right-align">Načrtovano</td>
        </tr>
        <tr>
            <td>Število premier</td>
            <td class="cell-type-number"><?= number_format($model->getStPremier(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega velikih predstav</td>
            <td class="cell-type-number"><?= number_format($model->getStPremierVelikih(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega malih predstav</td>
            <td class="cell-type-number"><?= number_format($model->getStPremierMalih(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega malih koprodukcij</td>
            <td class="cell-type-number"><?= number_format($model->getStPremierMalihKopr(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega srednjih koprodukcij</td>
            <td class="cell-type-number"><?= number_format($model->getStPremierSredKopr(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega velikih koprodukcij</td>
            <td class="cell-type-number"><?= number_format($model->getStPremierVelikihKopr(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Število ponovitev iz prejšnjih sezon</td>
            <td class="cell-type-number"><?= number_format($model->getStPonPrem(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega velikih predstav</td>
            <td class="cell-type-number"><?= number_format($model->getStPonPrejVelikih(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega malih predstav</td>
            <td class="cell-type-number"><?= number_format($model->getStPonPrejMalih(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega malih koprodukcij</td>
            <td class="cell-type-number"><?= number_format($model->getStPonPrejMalihKopr(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega srednjih koprodukcij</td>
            <td class="cell-type-number"><?= number_format($model->getStPonPrejSredKopr(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega velikih koprodukcij</td>
            <td class="cell-type-number"><?= number_format($model->getStPonPrejVelikihKopr(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Celotna vrednost lastne produkcije in postprodukcije (ponovitev) - programski sklop 1</td>
            <td class="cell-type-number"><?= number_format($model->getVrPS1(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">Vrednost produkcije (do premiere)</td>
            <td class="cell-type-number"><?= number_format($model->getVrPS1Do(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">Vrednost ponovitev na matičnem odru</td>
            <td class="cell-type-number"><?= number_format($model->getVrPS1Mat(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">Vrednost ponovitev na gostovanjih po SLO in zamejstvu</td>
            <td class="cell-type-number"><?= number_format($model->getVrPS1GostovSZ(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Število vseh javnih nekomercialnih prireditev skupaj</td>
            <td class="cell-type-number"><?= number_format($model->getstIzvNekomerc(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Število izvedb premiernih produkcij</td>
            <td class="cell-type-number"><?= number_format($model->getStIzvPonPrem() + $model->getstIzvPrem(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega na domačem odru</td>
            <td class="cell-type-number"><?= number_format($model->getStIzvPonPremDoma() + $model->getStIzvPremDoma(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">na odru slovenskega ali zamejskega koproducenta</td>
            <td class="cell-type-number"><?= number_format($model->getStIzvPonPremKopr() + $model->getStIzvPremKopr(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega na gostovanjih po Sloveniji</td>
            <td class="cell-type-number"><?= number_format($model->getstIzvPonPremGost(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega na gostovanjih v zamejstvu</td>
            <td class="cell-type-number"><?= number_format($model->getstIzvPonPremZamejo(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega na gostovanjih v tujini</td>
            <td class="cell-type-number"><?= number_format($model->getStIzvPonPremInt(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">na odru koproducenta v tujini</td>
            <td class="cell-type-number"><?= number_format($model->getStIzvPonPremKoprInt(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Število izvedb ponovitev iz prejšnjih sezon</td>
            <td class="cell-type-number"><?= number_format($model->getstIzvPonPrej(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega na domačem odru</td>
            <td class="cell-type-number"><?= number_format($model->getStIzvPonPrejDoma(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">na odru slovenskega ali zamejskega koproducenta</td>
            <td class="cell-type-number"><?= number_format($model->getStIzvPonPrejKopr(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega na gostovanjih po Sloveniji</td>
            <td class="cell-type-number"><?= number_format($model->getstIzvPonPrejGost(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega na gostovanjih v zamejstvu</td>
            <td class="cell-type-number"><?= number_format($model->getstIzvPonPrejZamejo(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega na gostovanjih v tujini</td>
            <td class="cell-type-number"><?= number_format($model->getStIzvPonPrejInt(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">na odru koproducenta v tujini</td>
            <td class="cell-type-number"><?= number_format($model->getStIzvPonPrejKoprInt(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Število izvedb gostujočih predstav</td>
            <td class="cell-type-number"><?= number_format($model->getStIzvGostuj(), 0, ',', '.') ?></td>
        </tr>	
        <tr>
            <td>Število ostalih javnih nekomercialnih prireditev</td>
            <td class="cell-type-number"><?= number_format($model->getstIzvOstalihNek(), 2, ',', '.') ?></td>
        </tr>	
        <tr>
            <td>Število gostovanj po Sloveniji</td>
            <td class="cell-type-number"><?= number_format($model->getStIzvGostovanjSlo(), 2, ',', '.') ?></td>
        </tr>	
        <tr>
            <td>Število gostovanj v zamejstvu</td>
            <td class="cell-type-number"><?= number_format($model->getstIzvGostovanjZam(), 2, ',', '.') ?></td>
        </tr>	
        <tr>
            <td>Število mednarodnih gostovanj (brez zamejstva)</td>
            <td class="cell-type-number"><?= number_format($model->getStIzvGostovanjInt(), 0, ',', '.') ?></td>
        </tr>	
        <tr>
            <td>Število obiskovalcev vseh premiernih uprizoritev in njihovih ponovitev</td>
            <td class="cell-type-number"><?= number_format($model->getStObiskPonPrem() + $model->getStObiskPrem(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">na domačem odru</td>
            <td class="cell-type-number"><?= number_format($model->getStObiskPonPremDoma() + $model->getStObiskPremDoma(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">na odru slovenskega ali zamejskega koproducenta</td>
            <td class="cell-type-number"><?= number_format($model->getStObiskPonPremKopr() + $model->getStObiskPremKopr(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">na odru koproducenta iz tujine</td>
            <td class="cell-type-number"><?= number_format($model->getStObiskPonPremKoprInt(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">na gostovanjih po Sloveniji</td>
            <td class="cell-type-number"><?= number_format($model->getStObiskPonPremGost(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">na gostovanjih v zamejstvu</td>
            <td class="cell-type-number"><?= number_format($model->getStObiskPonPremZamejo(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">na mednarodnih gostovanjih (brez zamejstva)</td>
            <td class="cell-type-number"><?= number_format($model->getStObiskPonPremInt(), 0, ',', '.') ?></td>
        </tr>	
        <tr>
            <td>Število obiskovalcev vseh nekomercialnih prireditev</td>
            <td class="cell-type-number"><?= number_format($model->getStObiskNekom(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">V lastnih dvoranah ali matičnih prizoriščih</td>
            <td class="cell-type-number"><?= number_format($model->getStObiskNekomMat(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">Na gostovanjih po Sloveniji</td>
            <td class="cell-type-number"><?= number_format($model->getStObiskNekomGostSlo(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">Na gostovanjih v zamejstvu</td>
            <td class="cell-type-number"><?= number_format($model->getStObiskNekomGostZam(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">Na mednarodnih gostovanjih (brez zamejstva)</td>
            <td class="cell-type-number"><?= number_format($model->getStObiskNekomGostInt(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Povprečno število obiskovalcev na prireditev</td>
            <td class="cell-type-number"><?= number_format($model->GetAvgObiskPrired(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Povprečno število obiskovalcev na premierno uprizoritev in njene ponovitve</td>
            <td class="cell-type-number"><?= number_format($povprecnoObisk, 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Povprečna zasedenost lastnih dvoran (v % na predstavo)</td>
            <td class="cell-type-number"><?= number_format($model->getAvgZasedDvoran(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Povprečna cena vstopnice</td>
            <td class="cell-type-number"><?= number_format($model->GetAvgCenaVstopnice(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Število prodanih vstopnic</td>
            <td class="cell-type-number"><?= number_format($model->getStProdVstopnic(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Število koprodukcij</td>
            <td class="cell-type-number"><?= number_format($model->getStKoprodukcij(), 0, ',', '.') ?></td>    <!--  + $model->getStKoprodukcijInt() + $model->getStKoprodukcijNVO() -->
        </tr>
        <tr>
            <td>Število koprodukcij z mednarodnimi koproducenti</td>
            <td class="cell-type-number"><?= number_format($model->getStKoprodukcijInt(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Število koprodukcij s slovenskimi NVO</td>
            <td class="cell-type-number"><?= number_format($model->getStKoprodukcijNVO(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Število vseh zaposlenih v javnem zavodu</td>
            <td class="cell-type-number"><?= number_format($model->getStZaposlenih(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Število zaposlenih igralcev</td>
            <td class="cell-type-number"><?= number_format($model->getStZaposIgralcev(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Povprečna zasedenost zaposlenih igralcev (popvprečno število nastopov v letu)</td>
            <td class="cell-type-number"><?= number_format($model->getAvgStNastopovIgr(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Načrtovano število honorarnih zunanjih sodelavcev</td>
            <td class="cell-type-number"><?= number_format($model->getStHonorarnihZun(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega s statusom samozaposlenega v kulturi</td>
            <td class="cell-type-number"><?= number_format($model->getStHonorarnihZunSamoz(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega igralcev</td>
            <td class="cell-type-number"><?= number_format($model->getStHonorarnihZunIgr(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega igralcev, zaposlenih v drugih javnih zavodih</td>
            <td class="cell-type-number"><?= number_format($model->getStHonorarnihZunIgrTujJZ(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Višina sredstev iz mednarodnih virov - z razpisi pridobljena sredstva</td>
            <td class="cell-type-number"><?= number_format($model->getSredstvaInt(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Višina sredstev, namenjenih avtorskim honorarjem</td>
            <td class="cell-type-number"><?= number_format($model->getSredstvaAvt(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega za sodelavce s statusom samozaposlenega v kulturi</td>
            <td class="cell-type-number"><?= number_format($model->getSredstvaAvtSamoz(), 2, ',', '.') ?></td>
        </tr>
    </table>
</div>