<?php
/**
 * Partial tmpl za koproducente
 * User: Alesch
 * date: 21.9.2015
 */
?>

<?php foreach ($kop as $koprodukcija) {
    $imekop = $koprodukcija->getKoproducent() ? $koprodukcija->getKoproducent()->getPopa()->getNaziv() : '';
    ?>
    <tr>
        <td class="alineja"><?= $imekop ?></td>
        <td class="cell-type-number"><?= number_format($koprodukcija->getKpe(), 2, ',', '.') ?></td>
        <td class="cell-type-number"><?= number_format($koprodukcija->getDelez(), 2, ',', '.') ?></td>
    </tr>
<?php } ?>
