<?php
/**
 * Partial tmpl za koproducente
 * User: Alesch
 * date: 21.9.2015
 */

foreach ($kop as $koprodukcija) {
    $imekop = $koprodukcija->getKoproducent() ? $koprodukcija->getKoproducent()->getPopa()->getNaziv() : '';
    $delez  = $koprodukcija->getDelez(); ?>
    <tr>
        <td class="alineja"><?= $imekop ?></td>
        <td class="cell-type-number"><?= number_format($delez, 2, ',', '.') ?></td>
    </tr>
<?php } ?>