<?php
/**
 * Partial tmpl za koproducente
 * User: Alesch
 * date: 21.9.2015
 */
?>

<table>
<?php foreach ($kop as $koprodukcija) {
    $imekop = $koprodukcija->getKoproducent() ? $koprodukcija->getKoproducent()->getPopa()->getNaziv() : '';
    $delez  = $koprodukcija->getDelez(); 
    $kpe    = $koprodukcija->getKpe(); 
    ?>
    <tr>
        <td class="alineja"><?= $imekop ?></td>
        <td class="cell-type-number"><?= number_format($kpe, 2, ',', '.') ?></td>
        <td class="cell-type-number"><?= number_format($delez, 2, ',', '.') ?></td>
    </tr>
<?php } ?>
</table>