<?php
/**
 * tmpl za mednarodna gostovanja
 * User: Alesch
 * Date: 21.9.2015
 */
// 
$drugiViri       = $model->drugiViri;

// iz mednarodna gostovanja
$upr             = $model->uprizoritev->naslov;
$krajGos         = $model->krajGostovanja . ' / ' . $model->drzavaGostovanja->naziv;
$datumGos        = $model->datumGostovanja->format('d-m-Y');
$ustanovaGos     = $model->ustanova;
$stPonovitevGos  = number_format($model->ponoviInt, 0, ',', '.');
$stPonovitevKop  = number_format($model->ponoviKoprInt, 0, ',', '.');
$stGledalcev     = number_format($model->obiskInt, 0, ',', '.');
$stGledalcevKop  = number_format($model->obiskKoprInt, 0, ',', '.');
$organizator     = $model->gostitelj->naziv;
$transStro       = number_format($model->transportniStroski, 2, ',', '.');
$zunAvtHon       = number_format($model->avtorskiHonorarji, 2, ',', '.');
$celotniStro     = number_format($model->nasDelez, 2, ',', '.');
$celotnaVred     = number_format($model->celotnaVrednost, 2, ',', '.');        
$lastSredstva    = number_format($model->lastnaSredstva, 2, ',', '.');
$drugSredstva    = number_format($model->drugiJavni, 2, ',', '.');
?>
<div id="mednarodna">
    <h2>Mednarodna gostovanja - gostovanja javnega zavoda v tujini (brez Zamejstva)</h2>
    <table>
        <tr>
            <td>Naslov uprizoritve:</td>
            <td class="right-align"><?= $upr ?></td>
        </tr>
        <tr>
            <td>Kraj gostovanja in država:</td>
            <td class="right-align"><?= $krajGos ?></td>
        </tr>
        <tr>
            <td>Ustanova, v kateri se gostuje:</td>
            <td class="right-align"><?= $ustanovaGos ?></td>
        </tr>
        <tr>
            <td>Datum gostovanja:</td>
            <td class="cell-type-date"><?= $datumGos ?></td>
        </tr>
        <tr>
            <td>Število ponovitev v okviru gostovanja:</td>
            <td class="cell-type-number"><?= $stPonovitevGos ?></td>
        </tr>       
        <tr>
            <td>Število ponovitev na odru koproducenta v tujini:</td>
            <td class="cell-type-number"><?= $stPonovitevKop ?></td>
        </tr>       
        <tr>
            <td>Načrtovano št. gledalcev:</td>
            <td class="cell-type-number"><?= $stGledalcev ?></td>
        </tr>
        <tr>
            <td>Načrtovano št. gledalcev na odru koproducenta v tujini:</td>
            <td class="cell-type-number"><?= $stGledalcevKop ?></td>
        </tr>
        <tr>
            <td>Organizator (gostitelj)</td>
            <td class="right-align"><?= $organizator ?></td>
        </tr>
        <tr>
            <td>Transportni stroški opreme ter stroški prevozov ansambla in tehnike:</td>
            <td class="cell-type-number"><?= $transStro ?></td>
        </tr>
        <tr>
            <td>Stroški avtorskih honorarjev zunanjih sodelavcev:</td>
            <td class="cell-type-number"><?= $zunAvtHon ?></td>
        </tr>
        <tr>
            <td>Celotni stroški gostovanja:</td>
            <td class="cell-type-number"><?= $celotniStro ?></td>
        </tr>
        <tr>
            <td>Lastna sredstva:</td>
            <td class="cell-type-number"><?= $lastSredstva ?></td>
        </tr>

        <tr>
            <td>Drugi Viri:</td>
            <td></td>
        </tr>
        <?php
            $this->partialLoop()->setObjectKey('drugiViri');
            echo $this->partialLoop('drugiViri', $drugiViri);
        ?>
        <tr>
            <td>Vir druga ministrstva in lokalna skupnost:</td>
            <td class="cell-type-number"><?= $drugSredstva ?></td>
        </tr>
        <tr>
            <td>Celotna vrednost gostovanja:</td>
            <td class="cell-type-number"><?= $celotnaVred ?></td>
        </tr>
    </table>
    <h2>Vsebinska utemeljitev predloga:</h2>
</div>