<?php
/**
 * partial tmpl za ponovitve premier
 * User: Alesch
 * Date: 21.9.2015
 */

$drugiViri       = $model->drugiViri;

// iz Ponovitvepremiere
$upr             = $model->uprizoritev->naslov;
$naDomacemOdru   = $model->ponoviDoma;
$naGosSlo        = $model->ponoviGost;
$naGosZam        = $model->ponoviZamejo;
$obiskDoma       = $model->obiskDoma;
$obiskGosSlo     = $model->obiskGost;
$obiskGosZam     = $model->obiskZamejo;
$sredstvaMK      = $model->zaproseno;
$celotnaVred     = $model->celotnaVrednost;
// $vredPonMat      = $model->;
// $vredPonGos      = $model->;
$tant            = $model->tantieme;
$avtHonorar      = $model->avtorskiHonorarji;
$lastSredstva    = $model->lastnaSredstva;
// $vlozKop         = $model->;
// $vlozGos         = $model->;
// $vlozOst         = $model->;

?>
<div id="premiere">
    <h2>Ponovitve premier</h2>
    <table>
        <tr>
            <td>Naslov uprizoritve:</td>
            <td><?= $upr ?></td>
        </tr>
        <tr>
            <td>Načrtovano št. vseh ponovitev v letu 2015:</td>
            <td></td>
        </tr>
        <tr>
            <td> - na domačem odru:</td>
            <td class="cell-type-number"><?= $naDomacemOdru ?></td>
        </tr>
        <tr>
            <td> - na gostovanjih po Sloveniji:</td>
            <td class="cell-type-number"><?= $naGosSlo ?></td>
        </tr>
        <tr>
            <td> - na gostovanjih v zamejstvu:</td>
            <td class="cell-type-number"><?= $naGosZam ?></td>
        </tr>
        <tr>
            <td>Načrtovano št. vseh obiskovalcev:</td>
            <td></td>
        </tr>
        <tr>
            <td> - na domačem odru:</td>
            <td class="cell-type-number"><?= $obiskDoma ?></td>
        </tr>
        <tr>
            <td> - na gostovanjih po Sloveniji:</td>
            <td class="cell-type-number"><?= $obiskGosSlo ?></td>
        </tr>
        <tr>
            <td> - na gostovanjih v zamejstvu:</td>
            <td class="cell-type-number"><?= $obiskGosZam ?></td>
        </tr>
        <tr>
            <td>Zaprošena sredstva Ministrstva za kulturo:</td>
            <td class="cell-type-number"><?= $sredstvaMK ?></td>
        </tr>
        
        <tr>
            <td>Celotna vrednost ponovitev:</td>
            <td class="cell-type-number"><?= $celotnaVred ?></td>
        </tr>
        <tr>
            <td> - vrednost ponovitev na matičnem odru:</td>
            <td class="cell-type-number"><?= $vredPonMat ?></td>
        </tr>
        <tr>
            <td>vrednost ponovitev na gostovanjih po SLO in v zamejstvu:</td>
            <td class="cell-type-number"><?= $vredPonGos ?></td>
        </tr>
        <tr>
            <td>Stroški avtorskih honorarjev zunanjih sodelavcev:</td>
            <td class="cell-type-number"><?= $avtHonorar ?></td>
        </tr>
        <tr>
            <td>Stroški tantiem, vezanih na ponovitve:</td>
            <td class="cell-type-number"><?= $tant ?></td>
        </tr>
        <tr>
            <td>Lastna sredstva:</td>
            <td class="cell-type-number"><?= $lastSredstva ?></td>
        </tr>
        <tr>
            <td>Drugi Viri:</td>
            <td></td>
        </tr>
        <?php
            $this->partialLoop()->setObjectKey('drugiViri');
            echo $this->partialLoop('drugiViri', $drugiViri);
        ?>
        <tr>
            <td> - od tega vložek koproducenta:</td>
            <td class="cell-type-number"><?= $vlozKop ?></td>
        </tr>
        <tr>
            <td> - od tega vložek gostitelja:</td>
            <td class="cell-type-number"><?= $vlozGos ?></td>
        </tr>
        <tr>
            <td>Vir druga ministrstva in lokalna skupnost:</td>
            <td class="cell-type-number"><?= $vlozOst ?></td>
        </tr>
        <tr>
            <td><h2>Priloge:</h2></td>
            <td></td>
        </tr>
    </table>
</div>

