<?php
/**
 * tmpl za ponovitve prejšnjih uprizoritev
 * User: Alesch
 * Date: 21.9.2015
 */

$drugiViri       = $model->drugiViri;
$upr             = $model->uprizoritev;

// iz Ponovitve
$tipEnote        = $model->tipProgramskeEnote->naziv;
$koeEnote        = $model->kpe;
$stUmetnikov     = number_format($model->stZaposUmet, 0, ',', '.');
$stDrugih        = number_format($model->stZaposDrug, 0, ',', '.');
$stHonVsi        = number_format($model->stHonorarnih, 0, ',', '.');
$stHonIgr        = number_format($model->stHonorarnihIgr, 0, ',', '.');
$stHonTuj        = number_format($model->stHonorarnihIgrTujJZ, 0, ',', '.');
$stSamozap       = number_format($model->stHonorarnihIgrSamoz, 0, ',', '.');
$naDomacemOdru   = number_format($model->ponoviDoma, 0, ',', '.');
$naGosSlo        = number_format($model->ponoviGost, 0, ',', '.');
$naGosZam        = number_format($model->ponoviZamejo, 0, ',', '.');
$obiskDoma       = number_format($model->obiskDoma, 0, ',', '.');
$obiskGosSlo     = number_format($model->obiskGost, 0, ',', '.');
$obiskGosZam     = number_format($model->obiskZamejo, 0, ',', '.');
$sredstvaMK      = number_format($model->zaproseno, 2, ',', '.');
$celotnaVred     = number_format($model->celotnaVrednost, 2, ',', '.');
$vredPonMat      = number_format($model->celotnaVrednostMat, 2, ',', '.');
$vredPonGos      = number_format($model->celotnaVrednostGostovSZ, 2, ',', '.');
$tant            = number_format($model->tantieme, 2, ',', '.');
$avtHonorar      = number_format($model->avtorskiHonorarji, 2, ',', '.');
$lastSredstva    = number_format($model->lastnaSredstva, 2, ',', '.');
$vlozGos         = number_format($model->vlozekGostitelja, 2, ',', '.');
$vlozOst         = number_format($model->drugiJavni, 2, ',', '.');

?>
<div id="premiere">
    <h2>Ponovitve prejšnjih uprizoritev</h2>
    <table>
        <?php 
            echo $this->partial('uprizoritev', array('upr' => $upr)); 
        ?>
        <tr>
            <td>Tip programske enote:</td>
            <td  class="right-align"><?= $tipEnote ?></td>
        </tr>
        <tr>
            <td>Koeficient programske enote:</td>
            <td class="cell-type-number"><?= $koeEnote ?></td>
        </tr>
        <tr>
            <td>Št. zaposlenih čl. umetniškega ansambla, ki sodelujejo pri uprizoritvi:</td>
            <td class="cell-type-number"><?= $stUmetnikov ?></td>
        </tr>
        <tr>
            <td>Št. drugih zaposlenih, ki sodelujejo pri uprizoritvi (brez upravno-administrativnih delavcev):</td>
            <td class="cell-type-number"><?= $stDrugih ?></td>
        </tr>
        <tr>
            <td>Št. vseh, ki sodelujejo honorarno:</td>
            <td class="cell-type-number"><?= $stHonvsi ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega igralcev:</td>
            <td class="cell-type-number"><?= $stHonIgr ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega igralcev, zaposlenih v drugih javnih zavodih:</td>
            <td class="cell-type-number"><?= $stHonTuj ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega igralcev s statusom samozaposlenega v kulturi:</td>
            <td class="cell-type-number"><?= $stSamozap ?></td>
        </tr>
        <tr>
            <td>Načrtovano št. vseh ponovitev v letu 2015:</td>
            <td></td>
        </tr>
        <tr>
            <td class="alineja">na domačem odru:</td>
            <td class="cell-type-number"><?= $naDomacemOdru ?></td>
        </tr>
        <tr>
            <td class="alineja">na gostovanjih po Sloveniji:</td>
            <td class="cell-type-number"><?= $naGosSlo ?></td>
        </tr>
        <tr>
            <td class="alineja">na gostovanjih v zamejstvu:</td>
            <td class="cell-type-number"><?= $naGosZam ?></td>
        </tr>
        <tr>
            <td>Načrtovano št. vseh obiskovalcev:</td>
            <td></td>
        </tr>
        <tr>
            <td class="alineja">na domačem odru:</td>
            <td class="cell-type-number"><?= $obiskDoma ?></td>
        </tr>
        <tr>
            <td class="alineja">na gostovanjih po Sloveniji:</td>
            <td class="cell-type-number"><?= $obiskGosSlo ?></td>
        </tr>
        <tr>
            <td class="alineja">na gostovanjih v zamejstvu:</td>
            <td class="cell-type-number"><?= $obiskGosZam ?></td>
        </tr>
        <tr>
            <td>Zaprošena sredstva Ministrstva za kulturo:</td>
            <td class="cell-type-number"><?= $sredstvaMK ?></td>
        </tr>
        <tr>
            <td>Celotna vrednost ponovitev:</td>
            <td class="cell-type-number"><?= $celotnaVred ?></td>
        </tr>
        <tr>
            <td class="alineja">vrednost ponovitev na matičnem odru:</td>
            <td class="cell-type-number"><?= $vredPonMat ?></td>
        </tr>
        <tr>
            <td class="alineja">vrednost ponovitev na gostovanjih po SLO in v zamejstvu:</td>
            <td class="cell-type-number"><?= $vredPonGos ?></td>
        </tr>
        <tr>
            <td>Stroški avtorskih honorarjev zunanjih sodelavcev:</td>
            <td class="cell-type-number"><?= $avtHonorar ?></td>
        </tr>
        <tr>
            <td>Stroški tantiem, vezanih na ponovitve:</td>
            <td class="cell-type-number"><?= $tant ?></td>
        </tr>
        <tr>
            <td>Lastna sredstva:</td>
            <td class="cell-type-number"><?= $lastSredstva ?></td>
        </tr>
        <tr>
            <td>Drugi Viri:</td>
            <td></td>
        </tr>
        <?php
            $this->partialLoop()->setObjectKey('drugiViri');
            echo $this->partialLoop('drugiViri', $drugiViri);
        ?>
        <?php if($imakop) { ?>
            <tr>
                <td class="alineja">od tega vložek koproducenta:</td>
                <td></td>
            </tr>
            <?php
            echo $this->partial('koproducenti', array('kop' => $kop)); 
        } ?>
        <tr>
            <td class="alineja">od tega vložek gostitelja:</td>
            <td class="cell-type-number"><?= $vlozGos ?></td>
        </tr>
        <tr>
            <td>Vir druga ministrstva in lokalna skupnost:</td>
            <td class="cell-type-number"><?= $vlozOst ?></td>
        </tr>
    </table>
    <h2>Priloge:</h2>
</div>

