<?php
$skupaj = $postavke->getVrPremiere() +
        $postavke->getVrPonovitvePremier() +
        $postavke->getVrPonovitvePrejsnjih() +
        $postavke->getVrGostovanjaZamejstvo() +
        $postavke->getVrFestivali() +
        $postavke->getVrGostovanjaInt() +
        $postavke->getVrOstalo();
?>
<?php if ($postavke->getPodskupina() == '0') { ?>
    <tr class="suma-row">
        <td><?= $postavke->getSkupina() . '.' . $postavke->getPodSkupina() ?></td>
        <td><?= $postavke->getnaziv() ?></td>
        <td class="cell-type-number"><?= number_format($postavke->getVrPremiere(), 2, ',', '.') ?></td>
        <td class="cell-type-number"><?= number_format($postavke->getVrPonovitvePremier(), 2, ',', '.') ?></td>
        <td class="cell-type-number"><?= number_format($postavke->getVrPonovitvePrejsnjih(), 2, ',', '.') ?></td>
        <td class="cell-type-number"><?= number_format($postavke->getVrGostovanjaZamejstvo(), 2, ',', '.') ?></td>
        <td class="cell-type-number"><?= number_format($postavke->getVrFestivali(), 2, ',', '.') ?></td>
        <td class="cell-type-number"><?= number_format($postavke->getVrGostovanjaInt(), 2, ',', '.') ?></td>
        <td class="cell-type-number"><?= number_format($postavke->getVrOstalo(), 2, ',', '.') ?></td>
        <td class="cell-type-number"><?= number_format($skupaj, 2, ',', '.') ?></td>
    </tr>
<?php } else { ?>
    <tr>
        <td><?= $postavke->getSkupina() . '.' . $postavke->getPodSkupina() ?></td>
        <td><?= $postavke->getnaziv() ?></td>
        <td class="cell-type-number"><?= number_format($postavke->getVrPremiere(), 2, ',', '.') ?></td>
        <td class="cell-type-number"><?= number_format($postavke->getVrPonovitvePremier(), 2, ',', '.') ?></td>
        <td class="cell-type-number"><?= number_format($postavke->getVrPonovitvePrejsnjih(), 2, ',', '.') ?></td>
        <td class="cell-type-number"><?= number_format($postavke->getVrGostovanjaZamejstvo(), 2, ',', '.') ?></td>
        <td class="cell-type-number"><?= number_format($postavke->getVrFestivali(), 2, ',', '.') ?></td>
        <td class="cell-type-number"><?= number_format($postavke->getVrGostovanjaInt(), 2, ',', '.') ?></td>
        <td class="cell-type-number"><?= number_format($postavke->getVrOstalo(), 2, ',', '.') ?></td>
        <td class="cell-type-number"><?= number_format($skupaj, 2, ',', '.') ?></td>
    </tr>
<?php }; ?>
