<?php
$naslov   = !empty($this->title) ? $this->translate($this->title) : '';
$postavke = $model->getPostavkeC2;

// izračunam končne vsote
$sumaPremiere            = 0;
$sumaPonovitvePremier    = 0;
$sumaPonovitvePrejsnjih  = 0;
$sumaGostovanjaZamejstvo = 0;
$sumaFestivali           = 0;
$sumaGostovanjaInt       = 0;
$sumaOstalo              = 0;
$sumaSkupaj              = 0;

foreach ($postavke as $postavka) {
    if ($postavka->getPodskupina() == '0') {
        $sumaPremiere += $postavka->getVrPremiere();
        $sumaPonovitvePremier += $postavka->getVrPonovitvePremier();
        $sumaPonovitvePrejsnjih += $postavka->getVrPonovitvePrejsnjih();
        $sumaGostovanjaZamejstvo += $postavka->getVrGostovanjaZamejstvo();
        $sumaFestivali += $postavka->getVrFestivali();
        $sumaGostovanjaInt += $postavka->getVrGostovanjaInt();
        $sumaOstalo += $postavka->getVrOstalo();
        $sumaSkupaj += 
                $postavka->getVrPremiere() +
                $postavka->getVrPonovitvePremier() +
                $postavka->getVrPonovitvePrejsnjih() +
                $postavka->getVrGostovanjaZamejstvo() +
                $postavka->getVrFestivali() +
                $postavka->getVrGostovanjaInt() +
                $postavka->getVrOstalo();
    }
}
?> 
<div id="postavke-c2">
    <h2>Programski materialni stroški</h2>
    <table>
        <tr>
            <th class="cell-type-header-title">  </th>
            <th class="cell-type-header-title">Programski materialni stroški</th>
            <th class="cell-type-header-title right-align">Premiere</th>
            <th class="cell-type-header-title right-align">Ponovitve<br/> premiernih<br/> uprizoritev</th>
            <th class="cell-type-header-title right-align">Ponovitve iz<br/> prejšnjih let</th>
            <th class="cell-type-header-title right-align">Festivalske<br/> akcije</th>
            <th class="cell-type-header-title right-align">Gostovanja<br/> pri Slovencih<br/> v zamejstvu</th>
            <th class="cell-type-header-title right-align">Mednsrodna<br/> gostovanja</th>
            <th class="cell-type-header-title right-align">Ostalo</th>
            <th class="cell-type-header-title right-align">SKUPAJ</th>
        </tr>

        
        <?php if ($postavke) {
            $this->partialLoop()->setObjectKey('model');
            echo $this->partialLoop('postavka-c2', $model);
        } ?>

        <tr class="suma-row">
            <td class="cell-type-header-title">  </td>
            <td class="cell-type-header-title">SKUPAJ</td>
            <td class="cell-type-number"><?= number_format($sumaPremiere,2,',','.') ?></td>
            <td class="cell-type-number"><?= number_format($sumaPonovitvePremier,2,',','.') ?></td>
            <td class="cell-type-number"><?= number_format($sumaPonovitvePrejsnjih,2,',','.') ?></td>
            <td class="cell-type-number"><?= number_format($sumaFestivali,2,',','.') ?></td>
            <td class="cell-type-number"><?= number_format($sumaGostovanjaZamejstvo,2,',','.') ?></td>
            <td class="cell-type-number"><?= number_format($sumaGostovanjaInt,2,',','.') ?></td>
            <td class="cell-type-number"><?= number_format($sumaOstalo,2,',','.') ?></td>
            <td class="cell-type-number"><?= number_format($sumaSkupaj,2,',','.') ?></td>
        </tr>
    </table>
</div>
