<?php
/**
 * partial tmpl za premiere 
 * User: Alesch
 * Date: 21.9.2015
 *
 * @var ProgramDela\Entity\EnotaPrograma $model 
 */
// 

$upr             = $model->getUprizoritev();
$kop             = $model->getKoprodukcije();
$drugiViri       = $model->getDrugiViri();
$imakop          = $model->getImaKoprodukcije();
$trajanjeStudija = 'od ' . ($upr->getDatumZacStudija() ? $upr->getDatumZacStudija()->format('d-m-Y') : '' ) .
                   ' do ' . ($upr->getDatumPremiere() ? $upr->getDatumPremiere()->format('d-m-Y') : '');
$datumPremiere   = $upr->getDatumPremiere() ? $upr->getDatumPremiere()->format('d-m-Y') : '';
$prizorisce      = $model->getPriKoproducentu() ? 'pri koproducentu' : 'na matičnem odru';
?>
<div id="premiere">
    <h2>Uprizoritvena umetnost – Programski sklop I</h2>
    <h3>Premiere</h3>
    <table>
        <?php
            $this->partial()->setObjectKey('upr');
            echo $this->partial('uprizoritev', $upr);
        ?>
        <tr>
            <td>Št. zaposlenih čl. umetniškega ansambla, ki sodelujejo pri uprizoritvi:</td>
            <td class="cell-type-number"><?= number_format($model->getStZaposUmet(), 0, ',', '') ?></td>
        </tr>
        <tr>
            <td>Št. drugih zaposlenih, ki sodelujejo pri uprizoritvi (brez upravno-administrativnih delavcev):</td>
            <td class="cell-type-number"><?= number_format($model->getStZaposDrug(), 0, ',', '') ?></td>
        </tr>
        <tr>
            <td>Št. vseh, ki sodelujejo honorarno:</td>
            <td class="cell-type-number"><?= number_format($model->getStHonorarnih(), 0, ',', '') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega igralcev:</td>
            <td class="cell-type-number"><?= number_format($model->getStHonorarnihIgr(), 0, ',', '') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega igralcev, zaposlenih v drugih javnih zavodih:</td>
            <td class="cell-type-number"><?= number_format($model->getStHonorarnihIgrTujJZ(), 0, ',', '') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega igralcev s statusom samozaposlenega v kulturi:</td>
            <td class="cell-type-number"><?= number_format($model->getStHonorarnihIgrSamoz(), 0, ',', '') ?></td>
        </tr>
        <tr>
            <td>Trajanje študija (od-do):</td>
            <td class="right-align"><?= $trajanjeStudija ?></td>
        </tr>
        <tr>
            <td>Datum premiere:</td>
            <td class="cell-type-date"><?= $datumPremiere ?></td>
        </tr>
        <tr>
            <td>Prizorišče:</td>
            <td class="right-align"><?= $prizorisce ?></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Tip programske enote:</td>
            <td class="right-align"><?= $model->getTipProgramskeEnote() ? $model->getTipProgramskeEnote()->getNaziv() : '' ?></td>
        </tr>
        <tr>
            <td>Koeficient programske enote:</td>
            <td class="cell-type-number"><?= number_format($model->getKpe(), 2, ',', '') ?></td>
        </tr>
        <?php if ($imakop) { ?>
            <tr>
                <td>Koproducenti:</td>
                <td></td>
            </tr>
            <?php
                $this->partial()->setObjectKey('kop');
                echo $this->partial('koproducenti', $kop);
            ?>
        <?php } ?>
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>Zaprošena sredstva Ministrstva za kulturo:</td>
            <td class="cell-type-number"><?= number_format($model->getZaproseno(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Lastna sredstva:</td>
            <td class="cell-type-number"><?= number_format($model->getLastnaSredstva(), 2, ',', '.') ?></td>
        </tr>
        <?php if ($drugiViri) { ?>
            <tr class="suma-row">
                <td>Drugi Viri:</td>
                <td class="cell-type-number"><?= number_format($model->vsotaDrugihVirov(), 2, ',', '.') ?> </td>
            </tr>        
            <?php
            $this->partialLoop()->setObjectKey('drugiViri');
            echo $this->partialLoop('drugiViri.phtml', $drugiViri);
            ?>
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
        <?php } ?>
        <tr>
            <td>Vir druga ministrstva in lokalna skupnost:</td>
            <td class="cell-type-number"><?= number_format($model->getDrugiJavni(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Stroški avtorskih honorarjev do premiere:</td>
            <td class="cell-type-number"><?= number_format($model->getAvtorskiHonorarji(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Stroški odkupa avtorskih pravic:</td>
            <td class="cell-type-number"><?= number_format($model->getAvtorskePravice(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Stroški tantiem, vezanih na uprizoritev:</td>
            <td class="cell-type-number"><?= number_format($model->getTantieme(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Celotna vrednost uprizoritve do premiere:</td>
            <td class="cell-type-number"><?= number_format($model->getCelotnaVrednost(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td class="alineja">od tega stroški matičnega javnega zavoda:</td>
            <td class="cell-type-number"><?= number_format($model->getNasDelez(), 2, ',', '.') ?></td>
        </tr>
    </table>
    <h2>Priloge:</h2>
</div>
