<?php
/**
 * Partial za programske enote
 * User: Alesch
 * date: 21.9.2015
 */
?>

<tr>
    <td>Programska enota:</td>
    <td class="right-align"><?= $pEnote->naslovPE ?></td>
</tr>
<tr>
    <td>    - avtor:</td>
    <td class="right-align"><?= $pEnote->avtorPE ?></td>
</tr> 
<tr>
    <td>    - obseg:</td>
    <td class="right-align"><?= $pEnote->obsegPE ?></td>
</tr>
<tr>
    <td>    - mesec realizacije:</td>
    <td class="right-align"><?= $pEnote->mesecPE ?></td>
</tr>
<tr>
    <td>    - vrednost:</td>
    <td class="cell-type-number"><?= $pEnote->vrednostPE ?></td>
</tr>
