<?php
/**
 * Created by PhpStorm.
 * User: boris
 * Date: 17. 09. 15
 * Time: 15.59
 */

$tm             = !empty($this->margins[0]) ? $this->margins[0] : 17;
$lm             = !empty($this->margins[1]) ? $this->margins[1] : 15;
$bm             = !empty($this->margins[2]) ? $this->margins[2] : 17;
$rm             = !empty($this->margins[3]) ? $this->margins[3] : 15;
$pagesize       = $this->pageSize ? $this->pagesize : 'a4';
$orientation    = $this->orientation ? $this->orientation : 'p';
$isheaderfooter = $this->ishf;
$firmanaziv     = $this->firma->getNaziv();

if (is_array($title)) {
    $naslov = !empty($title[0]) ? $this->translate($title[0]) . ' ' . $title[1] : '';
} else {
    $naslov = !empty($title) ? $this->translate($title) : '';
}
?>

<!DOCTYPE html>
<html>
    <head>
        <title><h1><?= $naslov ?></h1></title>
        <meta charset="UTF-8">
        <style type="text/css">

            @page {
                sheet-size: <?= $pagesize . '-' . $orientation ?>;                
                size: auto;
                margin-top: <?= $tm ?>mm ;
                margin-left: <?= $lm ?>mm ;
                margin-bottom: <?= $bm ?>mm ;
                margin-right: <?= $rm ?>mm ;
                margin-footer: 5mm;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                font-size: 9px;
                odd-header-name: docHeader;
                even-header-name: docHeader;
                odd-footer-name: docFooter;
                even-footer-name: docFooter;
            };
            @media screen {
                #docHeader, #docFooter {
                    display: none;
                }
            }
            
            <?= $_css ? $this->partial($_css) : '' ?>

        </style>
    </head>
    <body>
        <!-- definicija glave in noge -->
        <?php if ($isheaderfooter) { ?>
            <htmlpageheader name="docHeader" id="docHeader"> 
                <table width="100%" style="topntail: 0; border-bottom: 1px solid #000000; vertical-align: bottom; color: #000088;">
                    <tr>
                        <td width="33%"><?= isset($firmanaziv) ? $firmanaziv : '' ?></td>
                        <td width="33%"></td>
                        <td width="33%" style="text-align: right; font-style: italic;"><?= $naslov ?></td>
                    </tr>
                </table>
            </htmlpageheader>
            <htmlpagefooter name="docFooter" id="docFooter">
                <table width="100%" style="topntail: 0; border-top: 1px solid #000000; vertical-align: bottom; color: #000088; font-weight: bold; font-style: italic;">
                    <tr>
                        <td width="33%">{DATE j.m.Y}</td>
                        <td width="33%"></td>
                        <td width="33%" style="text-align: right;"><?= $this->translate('Stran') ?>: {PAGENO}/{nbpg}</td>
                    </tr>
                </table>        
            </htmlpagefooter>       
            <sethtmlpageheader name="docHeader" page="all" value="ON" show-this-page="1" />
            <sethtmlpagefooter name="docFooter" page="all" value="ON" />
            <setpageheader name="docHeader" page="all" value="ON" />
            <setpagefooter name="docFooter" page="all" value="ON" />
        <?php } ?>
