<?php
/**
 * Partial za programske enote
 * User: Alesch
 * date: 21.9.2015
 */
?>

<tr>
    <td>Programska enota:</td>
    <td></td>
    <td class="right-align"><?= $pEnote->getNaslovPE() ?></td>
</tr>
<tr>
    <td class="alineja">avtor:</td>
    <td></td>
    <td class="right-align"><?= $pEnote->getAvtorPE() ?></td>
</tr> 
<tr>
    <td class="alineja">obseg:</td>
    <td></td>
    <td class="right-align"><?= $pEnote->getObsegPE() ?></td>
</tr>
<tr>
    <td class="alineja">mesec realizacije:</td>
    <td></td>
    <td class="right-align"><?= $pEnote->getMesecPE() ?></td>
</tr>
<tr>
    <td class="alineja">vrednost:</td>
    <td></td>
    <td class="cell-type-number"><?= number_format($pEnote->getVrednostPE(),2,',','.') ?></td>
</tr>
