<style>

    @page lezeca {sheet-size: A4-L;}
    @page pokoncna {sheet-size: A4-P;}

    #premiere {
        page-break-before: always;
    }

    #ponovitve-premier {
        page-break-before: always;
    }

    #ponovitve-prej {
        page-break-before: always;
    }

    #gostujoce {
        page-break-before: always;
    }

    #mednarodna {
        page-break-before: always;
    }

    #festivali {
        page-break-before: always;      
    }

    #razno {
        page-break-before: always;
    }

    #izjemni-dogodki {
        page-break-before: always;
    }

    #kazalniki {
        page-break-after: avoid;
        page: lezeca;        
    }

    #kazalniki-priloga {
        page: pokoncna;        
    }

    #postavke-c2 {
        page: lezeca;
    }

</style>

<div id="naslovnica">
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p class="glavni-naslov"><?= $naslov ?></p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>Izpisani sklopi:</p>
    <ul>
        <?= $jePs1 ? '<li>Programski sklop 1</li>' : '' ?>
        <?= $jePs2 ? '<li>Programski sklop 2</li>' : '' ?>
        <?= $jeKaz ? '<li>Kazalniki</li>' : '' ?>
        <?= $jeC2  ? '<li>Priloga C2</li>' : '' ?>
    </ul>
    <?= $jeZapis ? '' : 'Izpis brez prilog' ?>
</div>