<?php
/**
 * tmpl za razno
 * User: Alesch
 * Date: 21.9.2015
 */
// 

$drugiViri = $model->getDrugiViri();
$kop       = $model->getKoprodukcije();
$imakop    = $model->getImaKoprodukcije();
$pEnote    = $model->getProgramskeEnoteSklopa();

?>
<div id="razno">
    <h2>Uprizoritvena umetnost – Programski sklop II</h2>
    <h2>Razno</h2>
    <table>
        <tr class="suma-row">
            <td>Naziv Sklopa:</td>
            <td></td>
            <td class="right-align"><strong><?= $model->getNaziv() ?></strong></td>
        </tr>
        <?php
            $this->partialLoop()->setObjectKey('pEnote');
            echo $this->partialLoop('programske-enote', $pEnote);
        ?>
        <tr>
            <td>Št. programskih enot v sklopu:</td>
            <td></td>
            <td class="cell-type-number"><?= number_format($model->getStPE(), 0, ',', '.') ?></td>
        </tr>
        <?php if ($imakop) { ?>
            <tr class="suma-row">
                <td>Koproducenti:</td>
                <td class="cell-type-number">Koeficient</td>
                <td class="cell-type-number">Delež</td>
            </tr>
        <?php
            $this->partial()->setObjectKey('kop');
            echo $this->partial('koproducenti', $kop);
        ?>
        <?php } ?>
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>

        <tr>
            <td>Načrtovano število obiskovalcev:</td>
            <td></td>
            <td class="cell-type-number"><?= number_format($model->getObiskDoma(), 0, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Št. zaposlenih, ki sodelujejo pri izvedbi projekta:</td>
            <td></td>
            <td class="cell-type-number"><?= number_format($model->getStZaposlenih(), 0, ',', '.') ?></td>
        </tr>       
        <tr>
            <td>Št. vseh, ki sodelujejo honorarno pri izvedbi projekta in jim honorar izplačuje javni zavod:</td>
            <td></td>
            <td class="cell-type-number"><?= number_format($model->getStHonorarnihZun(), 0, ',', '.') ?></td>
        </tr>       
        <tr>
            <td>Zaprošena sredstva Ministrstva za kulturo:</td>
            <td></td>
            <td class="cell-type-number"><?= number_format($model->getZaproseno(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Lastna sredstva:</td>
            <td></td>
            <td class="cell-type-number"><?= number_format($model->getLastnaSredstva(), 2, ',', '.') ?></td>
        </tr>
        <?php if ($drugiViri) { ?>
            <tr class="suma-row">
                <td>Drugi Viri:</td>
                <td></td>
                <td class="cell-type-number"><?= number_format($model->vsotaDrugihVirov(), 2, ',', '.') ?> </td>
            </tr>        
            <?php
            $this->partialLoop()->setObjectKey('drugiViri');
            echo $this->partialLoop('drugiViri.phtml', $drugiViri);
            ?>
            <tr>
                <td>&nbsp;</td>
                <td></td>
                <td></td>
            </tr>
        <?php } ?>
        <tr>
            <td>Vir druga ministrstva in lokalna skupnost:</td>
            <td></td>
            <td class="cell-type-number"><?= number_format($model->getDrugiJavni(), 2, ',', '.') ?></td>
        </tr>
        <tr>
            <td>Celotna vrednost sklopa:</td>
            <td></td>
            <td class="cell-type-number"><?= number_format($model->getCelotnaVrednost(), 2, ',', '.') ?></td>
        </tr>
    </table>
    <h3>Vsebinska utemeljitev predloga - celotnega sklopa in posameznih enot:</h3>
</div>