<?php
/**
 * tmpl za razno
 * User: Alesch
 * Date: 21.9.2015
 */
// 
$drugiViri = $model->drugiViri;
$kop       = $model->koproducenti;
$pEnote    = $model->programskeEnoteSklopa;

$naziv        = $model->naziv;
$stEnot       = number_format($model->stPE, 0, ',', '.');
$stGledalcev  = number_format($model->obiskInt, 0, ',', '.');
$celotnaVred  = number_format($model->celotnaVrednost, 2, ',', '.');
$lastSredstva = number_format($model->lastnaSredstva, 2, ',', '.');
$drugSredstva = number_format($model->drugiJavni, 2, ',', '.');
$stZaposlenih = number_format($model->stZaposlenih, 0, ',', '.');
$stAvtHon     = number_format($model->stHonorarnih, 0, ',', '.');
$zaprSredstva = number_format($model->zaproseno, 2, ',', '.');
?>
<div id="razno">
    <h2>Razno</h2>
    <table>
        <tr>
            <td>Naziv Sklopa:</td>
            <td class="right-align"><?= $naziv ?></td>
        </tr>
        <?php
        $this->partialLoop()->setObjectKey('pEnote');
        echo $this->partialLoop('programske-enote', $pEnote);
        ?>
        <tr>
            <td>Št. programskih enot v sklopu:</td>
            <td class="cell-type-number"><?= $stEnot ?></td>
        </tr>

        <?php if ($imakop) { ?>
            <tr class="suma-row">
                <td>Koproducenti:</td>
                <td></td>
            </tr>
            <?php
            $this->partial()->setObjectKey('kop');
            echo $this->partial('koproducenti', $kop);
            ?>
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
        <?php } ?>

        <tr>
            <td>Načrtovano število obiskovalcev:</td>
            <td class="cell-type-number"><?= $stGledalcev ?></td>
        </tr>
        <tr>
            <td>Št. zaposlenih, ki sodelujejo pri izvedbi projekta:</td>
            <td class="cell-type-number"><?= $stZaposlenih ?></td>
        </tr>       
        <tr>
            <td>Št. vseh, ki sodelujejo honorarno pri izvedbi projekta in jim honorar izplačuje javni zavod:</td>
            <td class="cell-type-number"><?= $atAvtHon ?></td>
        </tr>       
        <tr>
            <td>Zaprošena sredstva Ministrstva za kulturo:</td>
            <td class="cell-type-number"><?= $zaprSredstva ?></td>
        </tr>
        <tr>
            <td>Lastna sredstva:</td>
            <td class="cell-type-number"><?= $lastSredstva ?></td>
        </tr>
        <?php if ($drugiViri) { ?>
            <tr class="suma-row">
                <td>Drugi Viri:</td>
                <td class="cell-type-number"><?= number_format($model->vsotaDrugihVirov(), 2, ',', '.') ?> </td>
            </tr>        
            <?php
            $this->partialLoop()->setObjectKey('drugiViri');
            echo $this->partialLoop('drugiViri.phtml', $drugiViri);
            ?>
            <tr>
                <td>&nbsp;</td>
                <td></td>
            </tr>
        <?php } ?>
        <tr>
            <td>Vir druga ministrstva in lokalna skupnost:</td>
            <td class="cell-type-number"><?= $drugSredstva ?></td>
        </tr>
        <tr>
            <td>Celotna vrednost sklopa:</td>
            <td class="cell-type-number"><?= $celotnaVred ?></td>
        </tr>
    </table>
    <h2>Vsebinska utemeljitev predloga - celotnega sklopa in posameznih enot:</h2>
</div>