<?php
/**
 * Partial tmpl za podatke o uprizoritvi
 * User: Alesch
 * date: 21.9.2015
 */
$fun = $this->upr->getFunkcije()->getAlternacije();;
?>

<tr>
    <td>Naslov uprizoritve:</td>
    <td class="right-align"><?= $this->upr->naslov ?></td>
</tr>
<tr>
    <td>Avtor:</td>
    <td class="right-align"><?= $this->upr->avtor ?></td>
</tr>

<tr>
    <td>Podnaslov:</td>
    <td class="right-align"><?= $this->upr->podnaslov ?></td>
</tr> 
<?php 
    $this->partialLoop()->setObjectKey('fun');
    echo $this->partialLoop('funkcija.phtml', $fun);
?>
