<?php
/**
 * Partial tmpl za podatke o uprizoritvi
 * User: Alesch
 * date: 21.9.2015
 */

$fun = $upr->getFunkcije();
?>

<tr>
    <td>Naslov uprizoritve:</td>
    <td class="right-align"><?= $upr->getNaslov() ?></td>
</tr>
<tr>
    <td>Zvrst uprizoritve:</td>
    <td class="right-align"><?= $upr->getZvrstUprizoritve() ? $upr->getZvrstUprizoritve()->getNaziv() : '' ?></td>
</tr>
<tr>
    <td>Avtor (pisec dela):</td>
    <td class="right-align"><?= $upr->getAvtor() ?></td>
</tr>

<tr>
    <td>Podnaslov:</td>
    <td class="right-align"><?= $upr->getPodnaslov() ?></td>
</tr> 
<?php 
    $this->partialLoop()->setObjectKey('fun');
    echo $this->partialLoop('funkcija.phtml', $fun);
?>
