<?php

/*
 *  Licenca GPLv3
 */

namespace Koledar\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
use DoctrineORMModule\Paginator\Adapter\DoctrinePaginator;

/**
 * Description of Gostovanja
 *
 * @author rado
 */
class Gostovanja
        extends \Max\Repository\AbstractMaxRepository
{

    protected $sortOptions = [
        "default" => [
            "vrsta" => ["alias" => "p.vrsta"]
        ],
        "vse"     => [
            "vrsta" => ["alias" => "p.vrsta"]
        ],
    ];

    public function getPaginator(array $options, $name = "default")
    {
        switch ($name) {
            case "default":
            case "vse":
                $qb   = $this->getVseQb($options);
                $sort = $this->getSort($name);
                $qb->orderBy($sort->order, $sort->dir);
                return new DoctrinePaginator(new Paginator($qb));
//            case "default":
//                $this->expect(!(empty($options['drzava']) ), "Država je obvezna", 770121);
//                $crit = new Criteria();
//                $e    = $crit->expr();
//
//                if (!empty($options['drzava'])) {
//                    $drzava = $this->getEntityManager()->find('App\Entity\Drzava', $options['drzava']);
//                    $exp    = $e->eq('drzava', $drzava);
//                }
//                $crit->andWhere($exp);
//                return new Selectable($this, $crit);
        }
    }

    public function getVseQb($options)
    {
        $qb = $this->createQueryBuilder('p');
        $e  = $qb->expr();
        if (!empty($options['q'])) {

            $naslov = $e->like('p.vrsta', ':vrsta');

            $qb->andWhere($e->orX($naslov));

            $qb->setParameter('vrsta', "{$options['q']}%", "string");
        }

        return $qb;
    }

    /**
     * Opravila pri ustvarjanju nove entitete
     *
     * @param Gostovanje $object
     * @param Parameters $params
     */
    public function create($object, $params = null)
    {
        if ($object->dogodek) {
            /** @var Dogodki $rep */
            $rep = $this->getEntityManager()->getRepository('Koledar\Entity\Dogodek');
            $rep->create($object->getDogodek(), $params);
        }
        parent::create($object, $params);
    }

    /**
     * 
     * @param type $object
     * @param type $params
     */
    public function update($object, $params = null)
    {
        if ($object->dogodek) {
            /** @var Dogodki $rep */
            $rep = $this->getEntityManager()->getRepository('Koledar\Entity\Dogodek');
            $rep->update($object->getDogodek(), $params);
        }
        parent::update($object, $params); // TODO: Change the autogenerated stub      
    }

    /**
     * Pri brisanju brišem tudi dogodek
     *
     * @param Predstava $object
     */
    public function delete($object)
    {
        parent::delete($object);
        $this->getEntityManager()->remove($object->getDogodek());
    }

}
