## YAML Template.
---
type: rest
entityClass: Prisotnost\Entity\Dodatek
forms:
    default: 
        elements:
#            - id
            - trajanje
            - prisotnost
            - tipdodatka
lists:
    default: 
        filter:
            elements:                 
                - name: prisotnost
                  type: toone
                  options:
                      label: Prisotnost
                      targetEntity: Prisotnost\Entity\Prisotnost
                      required: false
