## YAML Template.
---
type: rest
entityClass: Prisotnost\Entity\Dodatek
forms:
    default: 
        elements:
#            - id
            - trajanje
            - ura
            - tipdodatka
lists:
    default: 
        filter:
            elements:                 
                - name: ura
                  type: toone
                  options:
                      label: Ura
                      targetEntity: Prisotnost\Entity\Ura
                      required: false
