## YAML Template.
---
type: rest
entityClass: App\Entity\Option
forms:
    default: 
        elements:
            - name           
            - type           
            - defaultValue   
            - perUser        
            - readOnly       
            - public         
            - role           
            - description    