## YAML Template.
---
type: rest
entityClass: App\Entity\Option
disabledMethods:
    - create
    - update
    - delete
    
lists:    
    default:
        filter:
            elements: 
                - name: q
                  type: text
                  options:
                    required: false
                    placeholder: Išči..
                    label: Išči
        hydrator:
            exclude: [defaultValue]
            