## YAML Template.
---
type: rest
#    - list
#    - update
entityClass: App\Entity\OrganizacijskaEnota
forms:
    default: 
        elements:
#            - id
            - sifra
            - naziv
            - parent
#            - children
            - vodja
            - namestnik
#            - zaposlitve
lists:
    default: 
        hydrator:
            - exclude: []
        filter:
            elements:                 
                - name: parent
                  type: toone
                  options:
                      label: Parent
                      targetEntity: App\Entity\OrganizacijskaEnota
                      required: false
relation:
    default:
        zaposlitve:
            enabled: true
            hydrator:
                exclude: []
        children:
            enabled: true
            hydrator:
                exclude: []
