<?php
$sel = $this->plugin('selection');
?>
 <div class="col-md-6">
        <?php
        echo $sel->openTag('dodeljena');
        ?>
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <div class="btn-group pull-right" id="acl-tool">
                    <?php if ($action == 'urediDovoljenja') { ?>
                    <button class="btn btn-default btn-xs" name="toggleBtn" title="<?= $this->translate('Označi vse') ?>"><?= $sel->toggle('dodeljena') ?></button>
                    <input type="submit" class="btn btn-default btn-xs" name="removeSelectedBtn" value="<?= $this->translate('Odstrani izbrane',
                'default') ?>"></input>
                    <?php } ?>
                </div>
                <span class="pull-left"><?= $this->translate('Dodeljena dovoljenja', 'default') ?></span>
            </div>
            <ul class="list-group">
                <?php
                
                foreach ($dovoljenja as $r) {
                    ?>
                    <li class="list-group-item">
                        <h4 class="list-group-item-heading"><?= $action == 'urediDovoljenja' ? $sel->box($r->getId()): '' ?> <?= $r->getName() ?></h4>
                        <p class="list-group-item-content"> <?= $r->getDescription() ?></p>

                    </li>
<?php } ?>
            </ul>
        </div>
        <?php
        echo $sel->closeTag();
        ?>
    </div>