<?php
$this->headTitle()->append('Vloge');
$formType = 'inline';
$tf = $this->plugin('tipformat');
$ma = $this->plugin('marionette');
$ma->filter($filter);
?>

<div class="page-header">
    <h2><?= $this->translate('Vloge', 'default') ?></h2>
</div>

<table class="table table-condensed table-hover">
    <thead>
        <tr>
            <th><?= $this->translate('Naziv', 'default') ?></th>
            <th><?= $this->translate('Opis', 'default') ?></th>
            <th><?= $this->translate('Akcije', 'default') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        if ($paginator) {
            foreach ($paginator as $role) {
                echo $this->partial('aaa/role/listitem', ['role' => $role]);
            }
        }
        ?>
    </tbody>
</table>
<div class="row">
    <div class="col-md-12">
        <?php
        if ($paginator) {
            echo $this->paginationControl($paginator, 'sliding', 'tip/paginator/standard', array());
        }
        ?>
    </div>
</div>
