<tr>
    <td>
        <a href="<?=
        $this->newtab('aaa', ['id' => $role->id,
            'controller' => 'Role',
            'action' => 'pregled'
        ])
        ?>"><?= $role->name ?></a>
    </td>
    <td>
        <?= $role->description ?>
    </td>
    <td>
        <a href="<?=
        $this->url('aaa', ['id' => $role->id,
            'controller' => 'Role',
            'action' => 'brisi'
        ])
        ?>"><i class="icon-trash"></i></a>
        <a href="<?=
        $this->newtab('aaa', ['id' => $role->id,
            'controller' => 'Role',
            'action' => 'uredi',
        ])
        ?>"><i class="icon-edit"></i></a>
    </td>
</tr>
