<?php
$sel = $this->plugin('selection');
?>
    <div class="col-md-6">
<?= $sel->openTag("vloge") ?>
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <div class="btn-group pull-left">
                    <button class="btn btn-default btn-xs" name="toggleBtn" title="<?= $this->translate('Označi vse', 'default') ?>"><?= $sel->toggle('dodeljena') ?></button>
                    <input type="submit" class="btn btn-default btn-xs" name="addSelectedBtn" value="<?= $this->translate('Dodaj izbrane',
        'default') ?>"></input>
                    <a class="btn btn-default btn-xs" href="<?=
                    $this->url('aaa',
                            [
                        'controller' => 'Role',
                        'action' => 'uredi',
                        'id' => $object->getId()], ['query' => ['parent' => '']]);
                    ?>"><i class="icon-level-up"></i> </a>
                </div>
                <span class="pull-right"><?= $this->translate("Vloge") ?></span>


            </div>

            <ul class="list-group">
                <?php
                foreach ($dovoljenja as $r) {
                    ?>
                    <li class="list-group-item">
                        <h4 class="list-group-item-heading"><?= $sel->box($r->getId()) ?> <?= $r->getName() ?></h4>
                        <p class="list-group-item-content"> <?= $r->getDescription() ?></p>

                    </li>
                    <?php
                }
                echo $sel->closeTag();
                ?>
            </ul>
        </div>
    </div>