<?php
$this->headTitle()->append($meta->getI18n()->label);
$tf = $this->plugin('tipformat');
if ($form) {
    $form->prepare();
    $formHelper = $this->plugin('formtwb');

    $fs = $form->getBaseFieldset();
    $helper = $this->plugin('forminputtwb');
    $groupHelper = $this->plugin('formgrouptwb');

    $sel = $this->plugin('selection');

    echo $formHelper->openTag($form);
    ?>
    <div class="row">
        <div class="col-md-12">
            <?=
            $groupHelper->render($form, 'Vloga')
            ?>
            <?=
            $helper->render($form->get('csrf'));            
            ?>
            <?= $form->has('id')? $helper->render($form->get('id')) : '' ?>
        </div>
    </div>
    <?= $formHelper->closeTag($form); ?>


    <div class="row">
        <?= $this->roleList ?>
       <?= $this->partial('aaa/role/assigned-permissions', ['dovoljenja' => $object->getPermissions(), 'action' => 'pregled']) ?>
    </div>

    <div class = "row">
        <div class = "col-md-9">
            <?= $tf->zadnjaSprememba($object) ?>
        </div>
    </div>

    <?php
}
?>

