<?php
$tf = $this->plugin('tipformat');
$sel = $this->plugin('selection');
?>
<div class="col-md-6">
    <?= $sel->openTag("vloge") ?>
    <div class="panel panel-default">
        <div class="panel-heading clearfix">
            <div class="btn-group pull-left">
                <button class="btn btn-default btn-xs" name="toggleBtn" title="<?= $this->translate('Označi vse') ?>"><?= $sel->toggle('dodeljena') ?></button>
                <input type="submit" class="btn btn-default btn-xs" name="addSelectedBtn" value="<?=
                $this->translate('Dodaj izbrane', 'default')
                ?>"></input>
                <a class="btn btn-default btn-xs" href="<?=
                $this->url(null, [], ['query' => ['parent' => '']], true);
                ?>"><i class="icon-level-up"></i> </a>
            </div>
            <span class="pull-right"><?= $this->translate('Vloge', 'default') ?></span>
        </div>

        <ul class="list-group">
            <?php
            foreach ($vloge as $r) {
                ?>
                <li class="list-group-item">
                    <h4 class="list-group-item-heading"><?= $sel->box($r->getId()) ?> <?= $r->getName() ?> <?php
                        if ($r->hasChildren()) {
                            ?> <a href="<?=
                            $this->url(null, [], [ 'query' => ['parent' => $r->getId()]], true);
                            ?>"><i class="icon-level-down"></i></a>
                           <?php } ?>
                    </h4>
                    <p class="list-group-item-content"> <?= $r->getDescription() ?></p>
                </li>
                <?php
            }
            echo $sel->closeTag();
            ?>
        </ul>
    </div>
</div>
