<?php
$this->headTitle()->append($meta->getI18n()->label);
$tf = $this->plugin('tipformat');
$form->prepare();
$formHelper = $this->plugin('formtwb');
$fs = $form->getBaseFieldset();
$helper = $this->plugin('forminputtwb');
$groupHelper = $this->plugin('formgrouptwb');

$sel = $this->plugin('selection');

echo $formHelper->openTag($form);
?>
<div class="row">
    <div class="col-md-12">
        <?=
        $groupHelper->render($form, 'Vloga')
        ?>
        <?=
        $helper->render($form->get('csrf'));
        ?>
    </div>
</div>
<?= $formHelper->closeTag($form); ?>

<div class="row">   
    <?= $this->partial('aaa/role/assigned-permissions', ['dovoljenja' => $object->getPermissions(), 'action' => 'uredi']) ?>
    <?= $this->partial('aaa/role/permission-list', ['dovoljenja' => $dovoljenja, 'object' => $object, 'action' => 'uredi']) ?>
</div>

<div class = "row">
    <div class = "col-md-9">
        <?= $tf->zadnjaSprememba($object) ?>
    </div>
</div>



